export const TYPE_PERSONNEL_CODES = {
    ENSEIGNANT: 'TYPE_ENSEIGNANT',
    DIRECTION: 'TYPE_DIRECTION',
    ADMINISTRATIF: 'TYPE_ADMINISTRATIF',
    TECHNIQUE: 'TYPE_TECHNIQUE',
    SERVICE: 'TYPE_SERVICE',
    SANTE: 'TYPE_SANTE',
    SOCIAL: 'TYPE_SOCIAL',
    AUTRE: 'TYPE_AUTRE',
} as const;

export type TypePersonnelCode = typeof TYPE_PERSONNEL_CODES[keyof typeof TYPE_PERSONNEL_CODES];
