export const TYPE_PERSONNEL_CODES = {
    ENSEIGNANT: 'ENSEIGNANT',
    DIRECTION: 'DIRECTION',
    ADMINISTRATIF: 'ADMINISTRATIF',
    TECHNIQUE: 'TECHNIQUE',
    SERVICE: 'SERVICE',
    STAGE: 'STAGE',
    TEMPORAIRE: 'TEMPORAIRE',
    AUTRE: 'AUTRE',
} as const;

export type TypePersonnelCode = typeof TYPE_PERSONNEL_CODES[keyof typeof TYPE_PERSONNEL_CODES];
