/**
 * ==================================
 * eLISAschool - Entité Audit Log
 * ==================================
 * Version: 1.0.0
 * Auteur: franck arlos chendjou
 * 
 * Journalisation des actions sensibles pour la sécurité et la traçabilité
 */

import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    CreateDateColumn,
    Index,
    ManyToOne,
    JoinColumn,
} from 'typeorm';
import { Utilisateur } from './utilisateur.entity';

/**
 * Types d'actions auditées
 */
export enum AuditAction {
    // Authentification
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    LOGIN_FAILED = 'LOGIN_FAILED',
    PASSWORD_CHANGE = 'PASSWORD_CHANGE',
    PASSWORD_RESET = 'PASSWORD_RESET',

    // Utilisateurs
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_DELETE = 'USER_DELETE',
    USER_SUSPEND = 'USER_SUSPEND',
    USER_ACTIVATE = 'USER_ACTIVATE',
    ROLE_CHANGE = 'ROLE_CHANGE',

    // Élevés
    ELEVE_CREATE = 'ELEVE_CREATE',
    ELEVE_UPDATE = 'ELEVE_UPDATE',
    ELEVE_DELETE = 'ELEVE_DELETE',
    ELEVE_INSCRIPTION = 'ELEVE_INSCRIPTION',

    // Bulletins
    BULLETIN_GENERATE = 'BULLETIN_GENERATE',
    BULLETIN_UPDATE = 'BULLETIN_UPDATE',

    // Académique
    CYCLE_CREATE = 'CYCLE_CREATE',
    CYCLE_UPDATE = 'CYCLE_UPDATE',
    CYCLE_DELETE = 'CYCLE_DELETE',
    NIVEAU_CREATE = 'NIVEAU_CREATE',
    NIVEAU_UPDATE = 'NIVEAU_UPDATE',
    NIVEAU_DELETE = 'NIVEAU_DELETE',
    CLASSE_CREATE = 'CLASSE_CREATE',
    CLASSE_UPDATE = 'CLASSE_UPDATE',
    CLASSE_DELETE = 'CLASSE_DELETE',
    MATIERE_CREATE = 'MATIERE_CREATE',
    MATIERE_UPDATE = 'MATIERE_UPDATE',
    MATIERE_DELETE = 'MATIERE_DELETE',
    PERIODE_CREATE = 'PERIODE_CREATE',
    PERIODE_UPDATE = 'PERIODE_UPDATE',
    PERIODE_DELETE = 'PERIODE_DELETE',
    ANNEE_SCOLAIRE_CREATE = 'ANNEE_SCOLAIRE_CREATE',
    ANNEE_SCOLAIRE_UPDATE = 'ANNEE_SCOLAIRE_UPDATE',
    ANNEE_SCOLAIRE_DELETE = 'ANNEE_SCOLAIRE_DELETE',
    ANNEE_SCOLAIRE_ACTIVATE = 'ANNEE_SCOLAIRE_ACTIVATE',

    // Établissement
    ETABLISSEMENT_CREATE = 'ETABLISSEMENT_CREATE',
    ETABLISSEMENT_UPDATE = 'ETABLISSEMENT_UPDATE',
    ETABLISSEMENT_DELETE = 'ETABLISSEMENT_DELETE',

    // Personnel
    PERSONNEL_CREATE = 'PERSONNEL_CREATE',
    PERSONNEL_UPDATE = 'PERSONNEL_UPDATE',
    PERSONNEL_DELETE = 'PERSONNEL_DELETE',
    CONTRAT_PERSONNEL_CREATE = 'CONTRAT_PERSONNEL_CREATE',
    CONTRAT_PERSONNEL_UPDATE = 'CONTRAT_PERSONNEL_UPDATE',
    CONTRAT_PERSONNEL_DELETE = 'CONTRAT_PERSONNEL_DELETE',
    TYPE_CONTRAT_CREATE = 'TYPE_CONTRAT_CREATE',
    TYPE_CONTRAT_UPDATE = 'TYPE_CONTRAT_UPDATE',
    TYPE_CONTRAT_DELETE = 'TYPE_CONTRAT_DELETE',
    AFFECTATION_POSTE_CREATE = 'AFFECTATION_POSTE_CREATE',
    AFFECTATION_POSTE_UPDATE = 'AFFECTATION_POSTE_UPDATE',
    AFFECTATION_POSTE_TERMINER = 'AFFECTATION_POSTE_TERMINER',
    MUTATION_HIERARCHIQUE = 'MUTATION_HIERARCHIQUE',
    HEURE_COURS_CREATE = 'HEURE_COURS_CREATE',
    HEURE_COURS_UPDATE = 'HEURE_COURS_UPDATE',
    HEURE_COURS_DELETE = 'HEURE_COURS_DELETE',
    ABSENCE_PERSONNEL_CREATE = 'ABSENCE_PERSONNEL_CREATE',
    ABSENCE_PERSONNEL_UPDATE = 'ABSENCE_PERSONNEL_UPDATE',
    ABSENCE_PERSONNEL_DELETE = 'ABSENCE_PERSONNEL_DELETE',
    ABSENCE_PERSONNEL_JUSTIFIER = 'ABSENCE_PERSONNEL_JUSTIFIER',
    EVALUATION_ENSEIGNANT_CREATE = 'EVALUATION_ENSEIGNANT_CREATE',
    EVALUATION_ENSEIGNANT_UPDATE = 'EVALUATION_ENSEIGNANT_UPDATE',
    EVALUATION_ENSEIGNANT_DELETE = 'EVALUATION_ENSEIGNANT_DELETE',
    PROGRESSION_PROGRAMME_CREATE = 'PROGRESSION_PROGRAMME_CREATE',
    PROGRESSION_PROGRAMME_UPDATE = 'PROGRESSION_PROGRAMME_UPDATE',
    PROGRESSION_PROGRAMME_DELETE = 'PROGRESSION_PROGRAMME_DELETE',
    PROGRAMME_CHAPITRE_CREATE = 'PROGRAMME_CHAPITRE_CREATE',
    PROGRAMME_CHAPITRE_UPDATE = 'PROGRAMME_CHAPITRE_UPDATE',
    PROGRAMME_CHAPITRE_DELETE = 'PROGRAMME_CHAPITRE_DELETE',
    BULLETIN_PAI_CREATE = 'BULLETIN_PAI_CREATE',
    BULLETIN_PAI_UPDATE = 'BULLETIN_PAI_UPDATE',
    BULLETIN_PAI_DELETE = 'BULLETIN_PAI_DELETE',
    BULLETIN_PAI_GENERER = 'BULLETIN_PAI_GENERER',
    BULLETIN_PAI_VALIDER = 'BULLETIN_PAI_VALIDER',

    // Documents
    DOCUMENT_CREATE = 'DOCUMENT_CREATE',
    DOCUMENT_DELETE = 'DOCUMENT_DELETE',
    DOCUMENT_PRINT = 'DOCUMENT_PRINT',
    DOCUMENT_GENERATE = 'DOCUMENT_GENERATE',

    // Suivi Élèves (nouveaux)
    INCIDENT_ELEVE_CREATE = 'INCIDENT_ELEVE_CREATE',
    INCIDENT_ELEVE_UPDATE = 'INCIDENT_ELEVE_UPDATE',
    SANCTION_ELEVE_CREATE = 'SANCTION_ELEVE_CREATE',
    SANCTION_ELEVE_UPDATE = 'SANCTION_ELEVE_UPDATE',
    FELICITATION_ELEVE_CREATE = 'FELICITATION_ELEVE_CREATE',
    OBSERVATION_ELEVE_CREATE = 'OBSERVATION_ELEVE_CREATE',

    // Suivi Personnel (nouveaux)
    INCIDENT_PERSONNEL_CREATE = 'INCIDENT_PERSONNEL_CREATE',
    INCIDENT_PERSONNEL_UPDATE = 'INCIDENT_PERSONNEL_UPDATE',
    EVALUATION_PERSONNEL_CREATE = 'EVALUATION_PERSONNEL_CREATE',
    EVALUATION_PERSONNEL_UPDATE = 'EVALUATION_PERSONNEL_UPDATE',

    // Santé (nouveaux)
    DOSSIER_MEDICAL_CREATE = 'DOSSIER_MEDICAL_CREATE',
    DOSSIER_MEDICAL_UPDATE = 'DOSSIER_MEDICAL_UPDATE',
    CONSULTATION_MEDICALE_CREATE = 'CONSULTATION_MEDICALE_CREATE',
    INCIDENT_SANTE_CREATE = 'INCIDENT_SANTE_CREATE',

    // Notes
    NOTE_CREATE = 'NOTE_CREATE',
    NOTE_UPDATE = 'NOTE_UPDATE',
    NOTE_DELETE = 'NOTE_DELETE',
    NOTE_VALIDATE = 'NOTE_VALIDATE',

    // Cantine
    MENU_CREATE = 'MENU_CREATE',
    MENU_UPDATE = 'MENU_UPDATE',
    MENU_DELETE = 'MENU_DELETE',
    INSCRIPTION_CANTINE_CREATE = 'INSCRIPTION_CANTINE_CREATE',
    INSCRIPTION_CANTINE_DELETE = 'INSCRIPTION_CANTINE_DELETE',
    SOLDE_RECHARGE = 'SOLDE_RECHARGE',
    CONSOMMATION_ENREGISTRER = 'CONSOMMATION_ENREGISTRER',

    // Transport
    LIGNE_CREATE = 'LIGNE_CREATE',
    LIGNE_UPDATE = 'LIGNE_UPDATE',
    LIGNE_DELETE = 'LIGNE_DELETE',
    INSCRIPTION_TRANSPORT_CREATE = 'INSCRIPTION_TRANSPORT_CREATE',
    INSCRIPTION_TRANSPORT_DELETE = 'INSCRIPTION_TRANSPORT_DELETE',
    PRESENCE_TRANSPORT = 'PRESENCE_TRANSPORT',

    // Cartes
    CARTE_CREATE = 'CARTE_CREATE',
    CARTE_UPDATE = 'CARTE_UPDATE',
    CARTE_DESACTIVER = 'CARTE_DESACTIVER',
    CARTE_RENOUVELER = 'CARTE_RENOUVELER',
    CARTE_PERTE = 'CARTE_PERTE',

    // Matériel
    MATERIEL_CREATE = 'MATERIEL_CREATE',
    MATERIEL_UPDATE = 'MATERIEL_UPDATE',
    MATERIEL_DELETE = 'MATERIEL_DELETE',
    MATERIEL_ASSIGN = 'MATERIEL_ASSIGN',
    MATERIEL_RETURN = 'MATERIEL_RETURN',

    // Messagerie
    MESSAGE_SEND = 'MESSAGE_SEND',
    MESSAGE_DELETE = 'MESSAGE_DELETE',
    MESSAGE_MARK_READ = 'MESSAGE_MARK_READ',

    // Clubs
    CLUB_CREATE = 'CLUB_CREATE',
    CLUB_UPDATE = 'CLUB_UPDATE',
    CLUB_DELETE = 'CLUB_DELETE',
    CLUB_JOIN = 'CLUB_JOIN',
    CLUB_LEAVE = 'CLUB_LEAVE',

    // Gamification
    BADGE_AWARD = 'BADGE_AWARD',
    SCORE_UPDATE = 'SCORE_UPDATE',
    GAMIFICATION_POINTS = 'GAMIFICATION_POINTS',
    GAMIFICATION_BADGE = 'GAMIFICATION_BADGE',
    GAMIFICATION_CLASSEMENT = 'GAMIFICATION_CLASSEMENT',

    // Sondages (nouveaux)
    SONDAGE_CREATE = 'SONDAGE_CREATE',
    SONDAGE_EDIT = 'SONDAGE_EDIT',
    SONDAGE_DELETE = 'SONDAGE_DELETE',
    SONDAGE_ACTIVATION = 'SONDAGE_ACTIVATION',

    // Annonces (nouveaux)
    ANNONCE_CREATE = 'ANNONCE_CREATE',
    ANNONCE_EDIT = 'ANNONCE_EDIT',
    ANNONCE_DELETE = 'ANNONCE_DELETE',
    ANNONCE_PUBLICATION = 'ANNONCE_PUBLICATION',

    // Santé - Actions détaillées (nouveaux)
    SANTE_INCIDENT = 'SANTE_INCIDENT',
    SANTE_VISITE = 'SANTE_VISITE',
    SANTE_CONSULTATION = 'SANTE_CONSULTATION',

    // Orientation
    ORIENTATION_CREATE = 'ORIENTATION_CREATE',
    ORIENTATION_UPDATE = 'ORIENTATION_UPDATE',
    ORIENTATION_VALIDATE = 'ORIENTATION_VALIDATE',

    // Requêtes
    REQUETE_CREATE = 'REQUETE_CREATE',
    REQUETE_EXECUTE = 'REQUETE_EXECUTE',
    REQUETE_DELETE = 'REQUETE_DELETE',

    // RBAC
    ROLE_CREATE = 'ROLE_CREATE',
    ROLE_UPDATE = 'ROLE_UPDATE',
    ROLE_DELETE = 'ROLE_DELETE',
    ROLE_ASSIGN = 'ROLE_ASSIGN',
    ROLE_REVOKE = 'ROLE_REVOKE',
    PERMISSION_CREATE = 'PERMISSION_CREATE',
    PERMISSION_UPDATE = 'PERMISSION_UPDATE',
    PERMISSION_DELETE = 'PERMISSION_DELETE',

    // Configuration
    CONFIG_CHANGE = 'CONFIG_CHANGE',
    MODULE_ACTIVATE = 'MODULE_ACTIVATE',
    MODULE_DEACTIVATE = 'MODULE_DEACTIVATE',

    // Préférences Utilisateur
    PREFERENCE_CREATE = 'PREFERENCE_CREATE',
    PREFERENCE_UPDATE = 'PREFERENCE_UPDATE',
    PREFERENCE_DELETE = 'PREFERENCE_DELETE',
    PREFERENCE_RESET = 'PREFERENCE_RESET',

    // Notifications
    NOTIFICATION_CREATE = 'NOTIFICATION_CREATE',
    NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE',
    NOTIFICATION_DELETE = 'NOTIFICATION_DELETE',
    NOTIFICATION_ENVOI_SUCCESS = 'NOTIFICATION_ENVOI_SUCCESS',
    NOTIFICATION_ENVOI_FAILURE = 'NOTIFICATION_ENVOI_FAILURE',
    NOTIFICATION_PROVIDER_CREATE = 'NOTIFICATION_PROVIDER_CREATE',
    NOTIFICATION_PROVIDER_UPDATE = 'NOTIFICATION_PROVIDER_UPDATE',
    NOTIFICATION_PROVIDER_DELETE = 'NOTIFICATION_PROVIDER_DELETE',
    NOTIFICATION_PROVIDER_TOGGLE = 'NOTIFICATION_PROVIDER_TOGGLE',
    NOTIFICATION_BULK_SEND = 'NOTIFICATION_BULK_SEND',

    // Finances
    PAYMENT_RECEIVE = 'PAYMENT_RECEIVE',
    REFUND = 'REFUND',

    // Données
    DATA_EXPORT = 'DATA_EXPORT',
    DATA_IMPORT = 'DATA_IMPORT',
    DATA_DELETE_BULK = 'DATA_DELETE_BULK',

    // Accès
    ACCESS_DENIED = 'ACCESS_DENIED',
    PERMISSION_CHANGE = 'PERMISSION_CHANGE',
}

/**
 * Niveau de sévérité
 */
export enum AuditSeverity {
    INFO = 'INFO',
    WARNING = 'WARNING',
    CRITICAL = 'CRITICAL',
}

/**
 * Entité AuditLog
 */
@Entity('audit_logs')
@Index(['utilisateurId', 'createdAt'])
@Index(['action', 'createdAt'])
@Index(['cible', 'cibleId'])
export class AuditLog {
    @PrimaryGeneratedColumn('uuid')
    id!: string;

    @Column({ type: 'uuid', nullable: true })
    utilisateurId?: string;

    @ManyToOne(() => Utilisateur, { nullable: true })
    @JoinColumn({ name: 'utilisateurId' })
    utilisateur?: Utilisateur;

    @Column({ type: 'enum', enum: AuditAction })
    action!: AuditAction;

    @Column({ type: 'enum', enum: AuditSeverity, default: AuditSeverity.INFO })
    severity!: AuditSeverity;

    @Column({ type: 'varchar', length: 100, nullable: true })
    cible?: string; // Type d'entité ciblée (Utilisateur, Note, Document, etc.)

    @Column({ type: 'uuid', nullable: true })
    cibleId?: string; // ID de l'entité ciblée

    @Column({ type: 'text', nullable: true })
    description?: string;

    @Column({ type: 'simple-json', nullable: true })
    anciennesValeurs?: Record<string, any>;

    @Column({ type: 'simple-json', nullable: true })
    nouvellesValeurs?: Record<string, any>;

    @Column({ type: 'varchar', length: 45, nullable: true })
    ipAddress?: string;

    @Column({ type: 'text', nullable: true })
    userAgent?: string;

    @Column({ type: 'varchar', length: 100, nullable: true })
    module?: string; // Module concerné

    @Column({ type: 'boolean', default: false })
    estEchec!: boolean;

    @Column({ type: 'text', nullable: true })
    erreur?: string;

    @CreateDateColumn({ type: 'timestamp' })
    createdAt!: Date;
}

export default AuditLog;
