/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUtilisateursRouteImport } from './routes/_auth.utilisateurs'
import { Route as AuthSpecialitesRouteImport } from './routes/_auth.specialites'
import { Route as AuthSallesRouteImport } from './routes/_auth.salles'
import { Route as AuthResponsablesElevesRouteImport } from './routes/_auth.responsables-eleves'
import { Route as AuthProgrammesRouteImport } from './routes/_auth.programmes'
import { Route as AuthPersonnelRouteImport } from './routes/_auth.personnel'
import { Route as AuthPeriodesRouteImport } from './routes/_auth.periodes'
import { Route as AuthParametresRouteImport } from './routes/_auth.parametres'
import { Route as AuthNotesRouteImport } from './routes/_auth.notes'
import { Route as AuthNiveauxRouteImport } from './routes/_auth.niveaux'
import { Route as AuthModulesRhRouteImport } from './routes/_auth.modules-rh'
import { Route as AuthModulesReportingRouteImport } from './routes/_auth.modules-reporting'
import { Route as AuthMatieresRouteImport } from './routes/_auth.matieres'
import { Route as AuthGroupesEtablissementsRouteImport } from './routes/_auth.groupes-etablissements'
import { Route as AuthFilieresRouteImport } from './routes/_auth.filieres'
import { Route as AuthExamensNationauxRouteImport } from './routes/_auth.examens-nationaux'
import { Route as AuthEtablissementsRouteImport } from './routes/_auth.etablissements'
import { Route as AuthElevesRouteImport } from './routes/_auth.eleves'
import { Route as AuthDiplomesElevesRouteImport } from './routes/_auth.diplomes-eleves'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCyclesRouteImport } from './routes/_auth.cycles'
import { Route as AuthConfigurationRouteImport } from './routes/_auth/configuration'
import { Route as AuthCompetencesRouteImport } from './routes/_auth.competences'
import { Route as AuthClassesRouteImport } from './routes/_auth.classes'
import { Route as AuthChangePasswordRouteImport } from './routes/_auth/change-password'
import { Route as AuthBulletinsRouteImport } from './routes/_auth.bulletins'
import { Route as AuthApparenceRouteImport } from './routes/_auth.apparence'
import { Route as AuthAnneesScolairesRouteImport } from './routes/_auth.annees-scolaires'
import { Route as AuthPeriodesIndexRouteImport } from './routes/_auth.periodes.index'
import { Route as AuthEtablissementsIndexRouteImport } from './routes/_auth.etablissements.index'
import { Route as AuthClassesIndexRouteImport } from './routes/_auth.classes.index'
import { Route as AuthAnneesScolairesIndexRouteImport } from './routes/_auth.annees-scolaires.index'
import { Route as AuthUtilisateursIdRouteImport } from './routes/_auth.utilisateurs.$id'
import { Route as AuthSallesStatistiquesRouteImport } from './routes/_auth.salles.statistiques'
import { Route as AuthSallesSalleIdRouteImport } from './routes/_auth.salles.$salleId'
import { Route as AuthPersonnelIdRouteImport } from './routes/_auth.personnel.$id'
import { Route as AuthPeriodesIdRouteImport } from './routes/_auth.periodes.$id'
import { Route as AuthMatieresIdRouteImport } from './routes/_auth.matieres.$id'
import { Route as AuthEtablissementsIdRouteImport } from './routes/_auth.etablissements.$id'
import { Route as AuthElevesIdRouteImport } from './routes/_auth.eleves.$id'
import { Route as AuthClassesIdRouteImport } from './routes/_auth.classes.$id'
import { Route as AuthAnneesScolairesIdRouteImport } from './routes/_auth.annees-scolaires.$id'
import { Route as AuthAdminRolesRouteImport } from './routes/_auth.admin.roles'
import { Route as AuthAdminPermissionsRouteImport } from './routes/_auth.admin.permissions'
import { Route as authenticatedParametresStructureAcademiqueRouteRouteImport } from './routes/(authenticated)/parametres/structure-academique/route'
import { Route as authenticatedParametresStructureAcademiqueNiveauxRouteImport } from './routes/(authenticated)/parametres/structure-academique/niveaux'
import { Route as authenticatedParametresStructureAcademiqueFilieresRouteImport } from './routes/(authenticated)/parametres/structure-academique/filieres'
import { Route as authenticatedParametresStructureAcademiqueExamensNationauxRouteImport } from './routes/(authenticated)/parametres/structure-academique/examens-nationaux'
import { Route as authenticatedParametresStructureAcademiqueDiplomesElevesRouteImport } from './routes/(authenticated)/parametres/structure-academique/diplomes-eleves'
import { Route as authenticatedParametresStructureAcademiqueCyclesRouteImport } from './routes/(authenticated)/parametres/structure-academique/cycles'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUtilisateursRoute = AuthUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSpecialitesRoute = AuthSpecialitesRouteImport.update({
  id: '/specialites',
  path: '/specialites',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSallesRoute = AuthSallesRouteImport.update({
  id: '/salles',
  path: '/salles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResponsablesElevesRoute = AuthResponsablesElevesRouteImport.update({
  id: '/responsables-eleves',
  path: '/responsables-eleves',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProgrammesRoute = AuthProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPersonnelRoute = AuthPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPeriodesRoute = AuthPeriodesRouteImport.update({
  id: '/periodes',
  path: '/periodes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthParametresRoute = AuthParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotesRoute = AuthNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNiveauxRoute = AuthNiveauxRouteImport.update({
  id: '/niveaux',
  path: '/niveaux',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModulesRhRoute = AuthModulesRhRouteImport.update({
  id: '/modules-rh',
  path: '/modules-rh',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModulesReportingRoute = AuthModulesReportingRouteImport.update({
  id: '/modules-reporting',
  path: '/modules-reporting',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMatieresRoute = AuthMatieresRouteImport.update({
  id: '/matieres',
  path: '/matieres',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGroupesEtablissementsRoute =
  AuthGroupesEtablissementsRouteImport.update({
    id: '/groupes-etablissements',
    path: '/groupes-etablissements',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthFilieresRoute = AuthFilieresRouteImport.update({
  id: '/filieres',
  path: '/filieres',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExamensNationauxRoute = AuthExamensNationauxRouteImport.update({
  id: '/examens-nationaux',
  path: '/examens-nationaux',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEtablissementsRoute = AuthEtablissementsRouteImport.update({
  id: '/etablissements',
  path: '/etablissements',
  getParentRoute: () => AuthRoute,
} as any)
const AuthElevesRoute = AuthElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDiplomesElevesRoute = AuthDiplomesElevesRouteImport.update({
  id: '/diplomes-eleves',
  path: '/diplomes-eleves',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCyclesRoute = AuthCyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfigurationRoute = AuthConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompetencesRoute = AuthCompetencesRouteImport.update({
  id: '/competences',
  path: '/competences',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClassesRoute = AuthClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBulletinsRoute = AuthBulletinsRouteImport.update({
  id: '/bulletins',
  path: '/bulletins',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApparenceRoute = AuthApparenceRouteImport.update({
  id: '/apparence',
  path: '/apparence',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnneesScolairesRoute = AuthAnneesScolairesRouteImport.update({
  id: '/annees-scolaires',
  path: '/annees-scolaires',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPeriodesIndexRoute = AuthPeriodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPeriodesRoute,
} as any)
const AuthEtablissementsIndexRoute = AuthEtablissementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthEtablissementsRoute,
} as any)
const AuthClassesIndexRoute = AuthClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthClassesRoute,
} as any)
const AuthAnneesScolairesIndexRoute =
  AuthAnneesScolairesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAnneesScolairesRoute,
  } as any)
const AuthUtilisateursIdRoute = AuthUtilisateursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthUtilisateursRoute,
} as any)
const AuthSallesStatistiquesRoute = AuthSallesStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => AuthSallesRoute,
} as any)
const AuthSallesSalleIdRoute = AuthSallesSalleIdRouteImport.update({
  id: '/$salleId',
  path: '/$salleId',
  getParentRoute: () => AuthSallesRoute,
} as any)
const AuthPersonnelIdRoute = AuthPersonnelIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthPersonnelRoute,
} as any)
const AuthPeriodesIdRoute = AuthPeriodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthPeriodesRoute,
} as any)
const AuthMatieresIdRoute = AuthMatieresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthMatieresRoute,
} as any)
const AuthEtablissementsIdRoute = AuthEtablissementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthEtablissementsRoute,
} as any)
const AuthElevesIdRoute = AuthElevesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthElevesRoute,
} as any)
const AuthClassesIdRoute = AuthClassesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthClassesRoute,
} as any)
const AuthAnneesScolairesIdRoute = AuthAnneesScolairesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthAnneesScolairesRoute,
} as any)
const AuthAdminRolesRoute = AuthAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminPermissionsRoute = AuthAdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => AuthRoute,
} as any)
const authenticatedParametresStructureAcademiqueRouteRoute =
  authenticatedParametresStructureAcademiqueRouteRouteImport.update({
    id: '/(authenticated)/parametres/structure-academique',
    path: '/parametres/structure-academique',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedParametresStructureAcademiqueNiveauxRoute =
  authenticatedParametresStructureAcademiqueNiveauxRouteImport.update({
    id: '/niveaux',
    path: '/niveaux',
    getParentRoute: () => authenticatedParametresStructureAcademiqueRouteRoute,
  } as any)
const authenticatedParametresStructureAcademiqueFilieresRoute =
  authenticatedParametresStructureAcademiqueFilieresRouteImport.update({
    id: '/filieres',
    path: '/filieres',
    getParentRoute: () => authenticatedParametresStructureAcademiqueRouteRoute,
  } as any)
const authenticatedParametresStructureAcademiqueExamensNationauxRoute =
  authenticatedParametresStructureAcademiqueExamensNationauxRouteImport.update({
    id: '/examens-nationaux',
    path: '/examens-nationaux',
    getParentRoute: () => authenticatedParametresStructureAcademiqueRouteRoute,
  } as any)
const authenticatedParametresStructureAcademiqueDiplomesElevesRoute =
  authenticatedParametresStructureAcademiqueDiplomesElevesRouteImport.update({
    id: '/diplomes-eleves',
    path: '/diplomes-eleves',
    getParentRoute: () => authenticatedParametresStructureAcademiqueRouteRoute,
  } as any)
const authenticatedParametresStructureAcademiqueCyclesRoute =
  authenticatedParametresStructureAcademiqueCyclesRouteImport.update({
    id: '/cycles',
    path: '/cycles',
    getParentRoute: () => authenticatedParametresStructureAcademiqueRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/annees-scolaires': typeof AuthAnneesScolairesRouteWithChildren
  '/apparence': typeof AuthApparenceRoute
  '/bulletins': typeof AuthBulletinsRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/classes': typeof AuthClassesRouteWithChildren
  '/competences': typeof AuthCompetencesRoute
  '/configuration': typeof AuthConfigurationRoute
  '/cycles': typeof AuthCyclesRoute
  '/dashboard': typeof AuthDashboardRoute
  '/diplomes-eleves': typeof AuthDiplomesElevesRoute
  '/eleves': typeof AuthElevesRouteWithChildren
  '/etablissements': typeof AuthEtablissementsRouteWithChildren
  '/examens-nationaux': typeof AuthExamensNationauxRoute
  '/filieres': typeof AuthFilieresRoute
  '/groupes-etablissements': typeof AuthGroupesEtablissementsRoute
  '/matieres': typeof AuthMatieresRouteWithChildren
  '/modules-reporting': typeof AuthModulesReportingRoute
  '/modules-rh': typeof AuthModulesRhRoute
  '/niveaux': typeof AuthNiveauxRoute
  '/notes': typeof AuthNotesRoute
  '/parametres': typeof AuthParametresRoute
  '/periodes': typeof AuthPeriodesRouteWithChildren
  '/personnel': typeof AuthPersonnelRouteWithChildren
  '/programmes': typeof AuthProgrammesRoute
  '/responsables-eleves': typeof AuthResponsablesElevesRoute
  '/salles': typeof AuthSallesRouteWithChildren
  '/specialites': typeof AuthSpecialitesRoute
  '/utilisateurs': typeof AuthUtilisateursRouteWithChildren
  '/parametres/structure-academique': typeof authenticatedParametresStructureAcademiqueRouteRouteWithChildren
  '/admin/permissions': typeof AuthAdminPermissionsRoute
  '/admin/roles': typeof AuthAdminRolesRoute
  '/annees-scolaires/$id': typeof AuthAnneesScolairesIdRoute
  '/classes/$id': typeof AuthClassesIdRoute
  '/eleves/$id': typeof AuthElevesIdRoute
  '/etablissements/$id': typeof AuthEtablissementsIdRoute
  '/matieres/$id': typeof AuthMatieresIdRoute
  '/periodes/$id': typeof AuthPeriodesIdRoute
  '/personnel/$id': typeof AuthPersonnelIdRoute
  '/salles/$salleId': typeof AuthSallesSalleIdRoute
  '/salles/statistiques': typeof AuthSallesStatistiquesRoute
  '/utilisateurs/$id': typeof AuthUtilisateursIdRoute
  '/annees-scolaires/': typeof AuthAnneesScolairesIndexRoute
  '/classes/': typeof AuthClassesIndexRoute
  '/etablissements/': typeof AuthEtablissementsIndexRoute
  '/periodes/': typeof AuthPeriodesIndexRoute
  '/parametres/structure-academique/cycles': typeof authenticatedParametresStructureAcademiqueCyclesRoute
  '/parametres/structure-academique/diplomes-eleves': typeof authenticatedParametresStructureAcademiqueDiplomesElevesRoute
  '/parametres/structure-academique/examens-nationaux': typeof authenticatedParametresStructureAcademiqueExamensNationauxRoute
  '/parametres/structure-academique/filieres': typeof authenticatedParametresStructureAcademiqueFilieresRoute
  '/parametres/structure-academique/niveaux': typeof authenticatedParametresStructureAcademiqueNiveauxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/apparence': typeof AuthApparenceRoute
  '/bulletins': typeof AuthBulletinsRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/competences': typeof AuthCompetencesRoute
  '/configuration': typeof AuthConfigurationRoute
  '/cycles': typeof AuthCyclesRoute
  '/dashboard': typeof AuthDashboardRoute
  '/diplomes-eleves': typeof AuthDiplomesElevesRoute
  '/eleves': typeof AuthElevesRouteWithChildren
  '/examens-nationaux': typeof AuthExamensNationauxRoute
  '/filieres': typeof AuthFilieresRoute
  '/groupes-etablissements': typeof AuthGroupesEtablissementsRoute
  '/matieres': typeof AuthMatieresRouteWithChildren
  '/modules-reporting': typeof AuthModulesReportingRoute
  '/modules-rh': typeof AuthModulesRhRoute
  '/niveaux': typeof AuthNiveauxRoute
  '/notes': typeof AuthNotesRoute
  '/parametres': typeof AuthParametresRoute
  '/personnel': typeof AuthPersonnelRouteWithChildren
  '/programmes': typeof AuthProgrammesRoute
  '/responsables-eleves': typeof AuthResponsablesElevesRoute
  '/salles': typeof AuthSallesRouteWithChildren
  '/specialites': typeof AuthSpecialitesRoute
  '/utilisateurs': typeof AuthUtilisateursRouteWithChildren
  '/parametres/structure-academique': typeof authenticatedParametresStructureAcademiqueRouteRouteWithChildren
  '/admin/permissions': typeof AuthAdminPermissionsRoute
  '/admin/roles': typeof AuthAdminRolesRoute
  '/annees-scolaires/$id': typeof AuthAnneesScolairesIdRoute
  '/classes/$id': typeof AuthClassesIdRoute
  '/eleves/$id': typeof AuthElevesIdRoute
  '/etablissements/$id': typeof AuthEtablissementsIdRoute
  '/matieres/$id': typeof AuthMatieresIdRoute
  '/periodes/$id': typeof AuthPeriodesIdRoute
  '/personnel/$id': typeof AuthPersonnelIdRoute
  '/salles/$salleId': typeof AuthSallesSalleIdRoute
  '/salles/statistiques': typeof AuthSallesStatistiquesRoute
  '/utilisateurs/$id': typeof AuthUtilisateursIdRoute
  '/annees-scolaires': typeof AuthAnneesScolairesIndexRoute
  '/classes': typeof AuthClassesIndexRoute
  '/etablissements': typeof AuthEtablissementsIndexRoute
  '/periodes': typeof AuthPeriodesIndexRoute
  '/parametres/structure-academique/cycles': typeof authenticatedParametresStructureAcademiqueCyclesRoute
  '/parametres/structure-academique/diplomes-eleves': typeof authenticatedParametresStructureAcademiqueDiplomesElevesRoute
  '/parametres/structure-academique/examens-nationaux': typeof authenticatedParametresStructureAcademiqueExamensNationauxRoute
  '/parametres/structure-academique/filieres': typeof authenticatedParametresStructureAcademiqueFilieresRoute
  '/parametres/structure-academique/niveaux': typeof authenticatedParametresStructureAcademiqueNiveauxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/annees-scolaires': typeof AuthAnneesScolairesRouteWithChildren
  '/_auth/apparence': typeof AuthApparenceRoute
  '/_auth/bulletins': typeof AuthBulletinsRoute
  '/_auth/change-password': typeof AuthChangePasswordRoute
  '/_auth/classes': typeof AuthClassesRouteWithChildren
  '/_auth/competences': typeof AuthCompetencesRoute
  '/_auth/configuration': typeof AuthConfigurationRoute
  '/_auth/cycles': typeof AuthCyclesRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/diplomes-eleves': typeof AuthDiplomesElevesRoute
  '/_auth/eleves': typeof AuthElevesRouteWithChildren
  '/_auth/etablissements': typeof AuthEtablissementsRouteWithChildren
  '/_auth/examens-nationaux': typeof AuthExamensNationauxRoute
  '/_auth/filieres': typeof AuthFilieresRoute
  '/_auth/groupes-etablissements': typeof AuthGroupesEtablissementsRoute
  '/_auth/matieres': typeof AuthMatieresRouteWithChildren
  '/_auth/modules-reporting': typeof AuthModulesReportingRoute
  '/_auth/modules-rh': typeof AuthModulesRhRoute
  '/_auth/niveaux': typeof AuthNiveauxRoute
  '/_auth/notes': typeof AuthNotesRoute
  '/_auth/parametres': typeof AuthParametresRoute
  '/_auth/periodes': typeof AuthPeriodesRouteWithChildren
  '/_auth/personnel': typeof AuthPersonnelRouteWithChildren
  '/_auth/programmes': typeof AuthProgrammesRoute
  '/_auth/responsables-eleves': typeof AuthResponsablesElevesRoute
  '/_auth/salles': typeof AuthSallesRouteWithChildren
  '/_auth/specialites': typeof AuthSpecialitesRoute
  '/_auth/utilisateurs': typeof AuthUtilisateursRouteWithChildren
  '/(authenticated)/parametres/structure-academique': typeof authenticatedParametresStructureAcademiqueRouteRouteWithChildren
  '/_auth/admin/permissions': typeof AuthAdminPermissionsRoute
  '/_auth/admin/roles': typeof AuthAdminRolesRoute
  '/_auth/annees-scolaires/$id': typeof AuthAnneesScolairesIdRoute
  '/_auth/classes/$id': typeof AuthClassesIdRoute
  '/_auth/eleves/$id': typeof AuthElevesIdRoute
  '/_auth/etablissements/$id': typeof AuthEtablissementsIdRoute
  '/_auth/matieres/$id': typeof AuthMatieresIdRoute
  '/_auth/periodes/$id': typeof AuthPeriodesIdRoute
  '/_auth/personnel/$id': typeof AuthPersonnelIdRoute
  '/_auth/salles/$salleId': typeof AuthSallesSalleIdRoute
  '/_auth/salles/statistiques': typeof AuthSallesStatistiquesRoute
  '/_auth/utilisateurs/$id': typeof AuthUtilisateursIdRoute
  '/_auth/annees-scolaires/': typeof AuthAnneesScolairesIndexRoute
  '/_auth/classes/': typeof AuthClassesIndexRoute
  '/_auth/etablissements/': typeof AuthEtablissementsIndexRoute
  '/_auth/periodes/': typeof AuthPeriodesIndexRoute
  '/(authenticated)/parametres/structure-academique/cycles': typeof authenticatedParametresStructureAcademiqueCyclesRoute
  '/(authenticated)/parametres/structure-academique/diplomes-eleves': typeof authenticatedParametresStructureAcademiqueDiplomesElevesRoute
  '/(authenticated)/parametres/structure-academique/examens-nationaux': typeof authenticatedParametresStructureAcademiqueExamensNationauxRoute
  '/(authenticated)/parametres/structure-academique/filieres': typeof authenticatedParametresStructureAcademiqueFilieresRoute
  '/(authenticated)/parametres/structure-academique/niveaux': typeof authenticatedParametresStructureAcademiqueNiveauxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/annees-scolaires'
    | '/apparence'
    | '/bulletins'
    | '/change-password'
    | '/classes'
    | '/competences'
    | '/configuration'
    | '/cycles'
    | '/dashboard'
    | '/diplomes-eleves'
    | '/eleves'
    | '/etablissements'
    | '/examens-nationaux'
    | '/filieres'
    | '/groupes-etablissements'
    | '/matieres'
    | '/modules-reporting'
    | '/modules-rh'
    | '/niveaux'
    | '/notes'
    | '/parametres'
    | '/periodes'
    | '/personnel'
    | '/programmes'
    | '/responsables-eleves'
    | '/salles'
    | '/specialites'
    | '/utilisateurs'
    | '/parametres/structure-academique'
    | '/admin/permissions'
    | '/admin/roles'
    | '/annees-scolaires/$id'
    | '/classes/$id'
    | '/eleves/$id'
    | '/etablissements/$id'
    | '/matieres/$id'
    | '/periodes/$id'
    | '/personnel/$id'
    | '/salles/$salleId'
    | '/salles/statistiques'
    | '/utilisateurs/$id'
    | '/annees-scolaires/'
    | '/classes/'
    | '/etablissements/'
    | '/periodes/'
    | '/parametres/structure-academique/cycles'
    | '/parametres/structure-academique/diplomes-eleves'
    | '/parametres/structure-academique/examens-nationaux'
    | '/parametres/structure-academique/filieres'
    | '/parametres/structure-academique/niveaux'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/apparence'
    | '/bulletins'
    | '/change-password'
    | '/competences'
    | '/configuration'
    | '/cycles'
    | '/dashboard'
    | '/diplomes-eleves'
    | '/eleves'
    | '/examens-nationaux'
    | '/filieres'
    | '/groupes-etablissements'
    | '/matieres'
    | '/modules-reporting'
    | '/modules-rh'
    | '/niveaux'
    | '/notes'
    | '/parametres'
    | '/personnel'
    | '/programmes'
    | '/responsables-eleves'
    | '/salles'
    | '/specialites'
    | '/utilisateurs'
    | '/parametres/structure-academique'
    | '/admin/permissions'
    | '/admin/roles'
    | '/annees-scolaires/$id'
    | '/classes/$id'
    | '/eleves/$id'
    | '/etablissements/$id'
    | '/matieres/$id'
    | '/periodes/$id'
    | '/personnel/$id'
    | '/salles/$salleId'
    | '/salles/statistiques'
    | '/utilisateurs/$id'
    | '/annees-scolaires'
    | '/classes'
    | '/etablissements'
    | '/periodes'
    | '/parametres/structure-academique/cycles'
    | '/parametres/structure-academique/diplomes-eleves'
    | '/parametres/structure-academique/examens-nationaux'
    | '/parametres/structure-academique/filieres'
    | '/parametres/structure-academique/niveaux'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/_auth/annees-scolaires'
    | '/_auth/apparence'
    | '/_auth/bulletins'
    | '/_auth/change-password'
    | '/_auth/classes'
    | '/_auth/competences'
    | '/_auth/configuration'
    | '/_auth/cycles'
    | '/_auth/dashboard'
    | '/_auth/diplomes-eleves'
    | '/_auth/eleves'
    | '/_auth/etablissements'
    | '/_auth/examens-nationaux'
    | '/_auth/filieres'
    | '/_auth/groupes-etablissements'
    | '/_auth/matieres'
    | '/_auth/modules-reporting'
    | '/_auth/modules-rh'
    | '/_auth/niveaux'
    | '/_auth/notes'
    | '/_auth/parametres'
    | '/_auth/periodes'
    | '/_auth/personnel'
    | '/_auth/programmes'
    | '/_auth/responsables-eleves'
    | '/_auth/salles'
    | '/_auth/specialites'
    | '/_auth/utilisateurs'
    | '/(authenticated)/parametres/structure-academique'
    | '/_auth/admin/permissions'
    | '/_auth/admin/roles'
    | '/_auth/annees-scolaires/$id'
    | '/_auth/classes/$id'
    | '/_auth/eleves/$id'
    | '/_auth/etablissements/$id'
    | '/_auth/matieres/$id'
    | '/_auth/periodes/$id'
    | '/_auth/personnel/$id'
    | '/_auth/salles/$salleId'
    | '/_auth/salles/statistiques'
    | '/_auth/utilisateurs/$id'
    | '/_auth/annees-scolaires/'
    | '/_auth/classes/'
    | '/_auth/etablissements/'
    | '/_auth/periodes/'
    | '/(authenticated)/parametres/structure-academique/cycles'
    | '/(authenticated)/parametres/structure-academique/diplomes-eleves'
    | '/(authenticated)/parametres/structure-academique/examens-nationaux'
    | '/(authenticated)/parametres/structure-academique/filieres'
    | '/(authenticated)/parametres/structure-academique/niveaux'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  authenticatedParametresStructureAcademiqueRouteRoute: typeof authenticatedParametresStructureAcademiqueRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/utilisateurs': {
      id: '/_auth/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AuthUtilisateursRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/specialites': {
      id: '/_auth/specialites'
      path: '/specialites'
      fullPath: '/specialites'
      preLoaderRoute: typeof AuthSpecialitesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/salles': {
      id: '/_auth/salles'
      path: '/salles'
      fullPath: '/salles'
      preLoaderRoute: typeof AuthSallesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/responsables-eleves': {
      id: '/_auth/responsables-eleves'
      path: '/responsables-eleves'
      fullPath: '/responsables-eleves'
      preLoaderRoute: typeof AuthResponsablesElevesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/programmes': {
      id: '/_auth/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof AuthProgrammesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/personnel': {
      id: '/_auth/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof AuthPersonnelRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/periodes': {
      id: '/_auth/periodes'
      path: '/periodes'
      fullPath: '/periodes'
      preLoaderRoute: typeof AuthPeriodesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/parametres': {
      id: '/_auth/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthParametresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notes': {
      id: '/_auth/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthNotesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/niveaux': {
      id: '/_auth/niveaux'
      path: '/niveaux'
      fullPath: '/niveaux'
      preLoaderRoute: typeof AuthNiveauxRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modules-rh': {
      id: '/_auth/modules-rh'
      path: '/modules-rh'
      fullPath: '/modules-rh'
      preLoaderRoute: typeof AuthModulesRhRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modules-reporting': {
      id: '/_auth/modules-reporting'
      path: '/modules-reporting'
      fullPath: '/modules-reporting'
      preLoaderRoute: typeof AuthModulesReportingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/matieres': {
      id: '/_auth/matieres'
      path: '/matieres'
      fullPath: '/matieres'
      preLoaderRoute: typeof AuthMatieresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/groupes-etablissements': {
      id: '/_auth/groupes-etablissements'
      path: '/groupes-etablissements'
      fullPath: '/groupes-etablissements'
      preLoaderRoute: typeof AuthGroupesEtablissementsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/filieres': {
      id: '/_auth/filieres'
      path: '/filieres'
      fullPath: '/filieres'
      preLoaderRoute: typeof AuthFilieresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/examens-nationaux': {
      id: '/_auth/examens-nationaux'
      path: '/examens-nationaux'
      fullPath: '/examens-nationaux'
      preLoaderRoute: typeof AuthExamensNationauxRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/etablissements': {
      id: '/_auth/etablissements'
      path: '/etablissements'
      fullPath: '/etablissements'
      preLoaderRoute: typeof AuthEtablissementsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/eleves': {
      id: '/_auth/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof AuthElevesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/diplomes-eleves': {
      id: '/_auth/diplomes-eleves'
      path: '/diplomes-eleves'
      fullPath: '/diplomes-eleves'
      preLoaderRoute: typeof AuthDiplomesElevesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cycles': {
      id: '/_auth/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof AuthCyclesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/configuration': {
      id: '/_auth/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof AuthConfigurationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/competences': {
      id: '/_auth/competences'
      path: '/competences'
      fullPath: '/competences'
      preLoaderRoute: typeof AuthCompetencesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classes': {
      id: '/_auth/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthClassesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/change-password': {
      id: '/_auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/bulletins': {
      id: '/_auth/bulletins'
      path: '/bulletins'
      fullPath: '/bulletins'
      preLoaderRoute: typeof AuthBulletinsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/apparence': {
      id: '/_auth/apparence'
      path: '/apparence'
      fullPath: '/apparence'
      preLoaderRoute: typeof AuthApparenceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/annees-scolaires': {
      id: '/_auth/annees-scolaires'
      path: '/annees-scolaires'
      fullPath: '/annees-scolaires'
      preLoaderRoute: typeof AuthAnneesScolairesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/periodes/': {
      id: '/_auth/periodes/'
      path: '/'
      fullPath: '/periodes/'
      preLoaderRoute: typeof AuthPeriodesIndexRouteImport
      parentRoute: typeof AuthPeriodesRoute
    }
    '/_auth/etablissements/': {
      id: '/_auth/etablissements/'
      path: '/'
      fullPath: '/etablissements/'
      preLoaderRoute: typeof AuthEtablissementsIndexRouteImport
      parentRoute: typeof AuthEtablissementsRoute
    }
    '/_auth/classes/': {
      id: '/_auth/classes/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthClassesIndexRouteImport
      parentRoute: typeof AuthClassesRoute
    }
    '/_auth/annees-scolaires/': {
      id: '/_auth/annees-scolaires/'
      path: '/'
      fullPath: '/annees-scolaires/'
      preLoaderRoute: typeof AuthAnneesScolairesIndexRouteImport
      parentRoute: typeof AuthAnneesScolairesRoute
    }
    '/_auth/utilisateurs/$id': {
      id: '/_auth/utilisateurs/$id'
      path: '/$id'
      fullPath: '/utilisateurs/$id'
      preLoaderRoute: typeof AuthUtilisateursIdRouteImport
      parentRoute: typeof AuthUtilisateursRoute
    }
    '/_auth/salles/statistiques': {
      id: '/_auth/salles/statistiques'
      path: '/statistiques'
      fullPath: '/salles/statistiques'
      preLoaderRoute: typeof AuthSallesStatistiquesRouteImport
      parentRoute: typeof AuthSallesRoute
    }
    '/_auth/salles/$salleId': {
      id: '/_auth/salles/$salleId'
      path: '/$salleId'
      fullPath: '/salles/$salleId'
      preLoaderRoute: typeof AuthSallesSalleIdRouteImport
      parentRoute: typeof AuthSallesRoute
    }
    '/_auth/personnel/$id': {
      id: '/_auth/personnel/$id'
      path: '/$id'
      fullPath: '/personnel/$id'
      preLoaderRoute: typeof AuthPersonnelIdRouteImport
      parentRoute: typeof AuthPersonnelRoute
    }
    '/_auth/periodes/$id': {
      id: '/_auth/periodes/$id'
      path: '/$id'
      fullPath: '/periodes/$id'
      preLoaderRoute: typeof AuthPeriodesIdRouteImport
      parentRoute: typeof AuthPeriodesRoute
    }
    '/_auth/matieres/$id': {
      id: '/_auth/matieres/$id'
      path: '/$id'
      fullPath: '/matieres/$id'
      preLoaderRoute: typeof AuthMatieresIdRouteImport
      parentRoute: typeof AuthMatieresRoute
    }
    '/_auth/etablissements/$id': {
      id: '/_auth/etablissements/$id'
      path: '/$id'
      fullPath: '/etablissements/$id'
      preLoaderRoute: typeof AuthEtablissementsIdRouteImport
      parentRoute: typeof AuthEtablissementsRoute
    }
    '/_auth/eleves/$id': {
      id: '/_auth/eleves/$id'
      path: '/$id'
      fullPath: '/eleves/$id'
      preLoaderRoute: typeof AuthElevesIdRouteImport
      parentRoute: typeof AuthElevesRoute
    }
    '/_auth/classes/$id': {
      id: '/_auth/classes/$id'
      path: '/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof AuthClassesIdRouteImport
      parentRoute: typeof AuthClassesRoute
    }
    '/_auth/annees-scolaires/$id': {
      id: '/_auth/annees-scolaires/$id'
      path: '/$id'
      fullPath: '/annees-scolaires/$id'
      preLoaderRoute: typeof AuthAnneesScolairesIdRouteImport
      parentRoute: typeof AuthAnneesScolairesRoute
    }
    '/_auth/admin/roles': {
      id: '/_auth/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthAdminRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/permissions': {
      id: '/_auth/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthAdminPermissionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(authenticated)/parametres/structure-academique': {
      id: '/(authenticated)/parametres/structure-academique'
      path: '/parametres/structure-academique'
      fullPath: '/parametres/structure-academique'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/parametres/structure-academique/niveaux': {
      id: '/(authenticated)/parametres/structure-academique/niveaux'
      path: '/niveaux'
      fullPath: '/parametres/structure-academique/niveaux'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueNiveauxRouteImport
      parentRoute: typeof authenticatedParametresStructureAcademiqueRouteRoute
    }
    '/(authenticated)/parametres/structure-academique/filieres': {
      id: '/(authenticated)/parametres/structure-academique/filieres'
      path: '/filieres'
      fullPath: '/parametres/structure-academique/filieres'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueFilieresRouteImport
      parentRoute: typeof authenticatedParametresStructureAcademiqueRouteRoute
    }
    '/(authenticated)/parametres/structure-academique/examens-nationaux': {
      id: '/(authenticated)/parametres/structure-academique/examens-nationaux'
      path: '/examens-nationaux'
      fullPath: '/parametres/structure-academique/examens-nationaux'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueExamensNationauxRouteImport
      parentRoute: typeof authenticatedParametresStructureAcademiqueRouteRoute
    }
    '/(authenticated)/parametres/structure-academique/diplomes-eleves': {
      id: '/(authenticated)/parametres/structure-academique/diplomes-eleves'
      path: '/diplomes-eleves'
      fullPath: '/parametres/structure-academique/diplomes-eleves'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueDiplomesElevesRouteImport
      parentRoute: typeof authenticatedParametresStructureAcademiqueRouteRoute
    }
    '/(authenticated)/parametres/structure-academique/cycles': {
      id: '/(authenticated)/parametres/structure-academique/cycles'
      path: '/cycles'
      fullPath: '/parametres/structure-academique/cycles'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueCyclesRouteImport
      parentRoute: typeof authenticatedParametresStructureAcademiqueRouteRoute
    }
  }
}

interface AuthAnneesScolairesRouteChildren {
  AuthAnneesScolairesIdRoute: typeof AuthAnneesScolairesIdRoute
  AuthAnneesScolairesIndexRoute: typeof AuthAnneesScolairesIndexRoute
}

const AuthAnneesScolairesRouteChildren: AuthAnneesScolairesRouteChildren = {
  AuthAnneesScolairesIdRoute: AuthAnneesScolairesIdRoute,
  AuthAnneesScolairesIndexRoute: AuthAnneesScolairesIndexRoute,
}

const AuthAnneesScolairesRouteWithChildren =
  AuthAnneesScolairesRoute._addFileChildren(AuthAnneesScolairesRouteChildren)

interface AuthClassesRouteChildren {
  AuthClassesIdRoute: typeof AuthClassesIdRoute
  AuthClassesIndexRoute: typeof AuthClassesIndexRoute
}

const AuthClassesRouteChildren: AuthClassesRouteChildren = {
  AuthClassesIdRoute: AuthClassesIdRoute,
  AuthClassesIndexRoute: AuthClassesIndexRoute,
}

const AuthClassesRouteWithChildren = AuthClassesRoute._addFileChildren(
  AuthClassesRouteChildren,
)

interface AuthElevesRouteChildren {
  AuthElevesIdRoute: typeof AuthElevesIdRoute
}

const AuthElevesRouteChildren: AuthElevesRouteChildren = {
  AuthElevesIdRoute: AuthElevesIdRoute,
}

const AuthElevesRouteWithChildren = AuthElevesRoute._addFileChildren(
  AuthElevesRouteChildren,
)

interface AuthEtablissementsRouteChildren {
  AuthEtablissementsIdRoute: typeof AuthEtablissementsIdRoute
  AuthEtablissementsIndexRoute: typeof AuthEtablissementsIndexRoute
}

const AuthEtablissementsRouteChildren: AuthEtablissementsRouteChildren = {
  AuthEtablissementsIdRoute: AuthEtablissementsIdRoute,
  AuthEtablissementsIndexRoute: AuthEtablissementsIndexRoute,
}

const AuthEtablissementsRouteWithChildren =
  AuthEtablissementsRoute._addFileChildren(AuthEtablissementsRouteChildren)

interface AuthMatieresRouteChildren {
  AuthMatieresIdRoute: typeof AuthMatieresIdRoute
}

const AuthMatieresRouteChildren: AuthMatieresRouteChildren = {
  AuthMatieresIdRoute: AuthMatieresIdRoute,
}

const AuthMatieresRouteWithChildren = AuthMatieresRoute._addFileChildren(
  AuthMatieresRouteChildren,
)

interface AuthPeriodesRouteChildren {
  AuthPeriodesIdRoute: typeof AuthPeriodesIdRoute
  AuthPeriodesIndexRoute: typeof AuthPeriodesIndexRoute
}

const AuthPeriodesRouteChildren: AuthPeriodesRouteChildren = {
  AuthPeriodesIdRoute: AuthPeriodesIdRoute,
  AuthPeriodesIndexRoute: AuthPeriodesIndexRoute,
}

const AuthPeriodesRouteWithChildren = AuthPeriodesRoute._addFileChildren(
  AuthPeriodesRouteChildren,
)

interface AuthPersonnelRouteChildren {
  AuthPersonnelIdRoute: typeof AuthPersonnelIdRoute
}

const AuthPersonnelRouteChildren: AuthPersonnelRouteChildren = {
  AuthPersonnelIdRoute: AuthPersonnelIdRoute,
}

const AuthPersonnelRouteWithChildren = AuthPersonnelRoute._addFileChildren(
  AuthPersonnelRouteChildren,
)

interface AuthSallesRouteChildren {
  AuthSallesSalleIdRoute: typeof AuthSallesSalleIdRoute
  AuthSallesStatistiquesRoute: typeof AuthSallesStatistiquesRoute
}

const AuthSallesRouteChildren: AuthSallesRouteChildren = {
  AuthSallesSalleIdRoute: AuthSallesSalleIdRoute,
  AuthSallesStatistiquesRoute: AuthSallesStatistiquesRoute,
}

const AuthSallesRouteWithChildren = AuthSallesRoute._addFileChildren(
  AuthSallesRouteChildren,
)

interface AuthUtilisateursRouteChildren {
  AuthUtilisateursIdRoute: typeof AuthUtilisateursIdRoute
}

const AuthUtilisateursRouteChildren: AuthUtilisateursRouteChildren = {
  AuthUtilisateursIdRoute: AuthUtilisateursIdRoute,
}

const AuthUtilisateursRouteWithChildren =
  AuthUtilisateursRoute._addFileChildren(AuthUtilisateursRouteChildren)

interface AuthRouteChildren {
  AuthAnneesScolairesRoute: typeof AuthAnneesScolairesRouteWithChildren
  AuthApparenceRoute: typeof AuthApparenceRoute
  AuthBulletinsRoute: typeof AuthBulletinsRoute
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthClassesRoute: typeof AuthClassesRouteWithChildren
  AuthCompetencesRoute: typeof AuthCompetencesRoute
  AuthConfigurationRoute: typeof AuthConfigurationRoute
  AuthCyclesRoute: typeof AuthCyclesRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDiplomesElevesRoute: typeof AuthDiplomesElevesRoute
  AuthElevesRoute: typeof AuthElevesRouteWithChildren
  AuthEtablissementsRoute: typeof AuthEtablissementsRouteWithChildren
  AuthExamensNationauxRoute: typeof AuthExamensNationauxRoute
  AuthFilieresRoute: typeof AuthFilieresRoute
  AuthGroupesEtablissementsRoute: typeof AuthGroupesEtablissementsRoute
  AuthMatieresRoute: typeof AuthMatieresRouteWithChildren
  AuthModulesReportingRoute: typeof AuthModulesReportingRoute
  AuthModulesRhRoute: typeof AuthModulesRhRoute
  AuthNiveauxRoute: typeof AuthNiveauxRoute
  AuthNotesRoute: typeof AuthNotesRoute
  AuthParametresRoute: typeof AuthParametresRoute
  AuthPeriodesRoute: typeof AuthPeriodesRouteWithChildren
  AuthPersonnelRoute: typeof AuthPersonnelRouteWithChildren
  AuthProgrammesRoute: typeof AuthProgrammesRoute
  AuthResponsablesElevesRoute: typeof AuthResponsablesElevesRoute
  AuthSallesRoute: typeof AuthSallesRouteWithChildren
  AuthSpecialitesRoute: typeof AuthSpecialitesRoute
  AuthUtilisateursRoute: typeof AuthUtilisateursRouteWithChildren
  AuthAdminPermissionsRoute: typeof AuthAdminPermissionsRoute
  AuthAdminRolesRoute: typeof AuthAdminRolesRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnneesScolairesRoute: AuthAnneesScolairesRouteWithChildren,
  AuthApparenceRoute: AuthApparenceRoute,
  AuthBulletinsRoute: AuthBulletinsRoute,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthClassesRoute: AuthClassesRouteWithChildren,
  AuthCompetencesRoute: AuthCompetencesRoute,
  AuthConfigurationRoute: AuthConfigurationRoute,
  AuthCyclesRoute: AuthCyclesRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDiplomesElevesRoute: AuthDiplomesElevesRoute,
  AuthElevesRoute: AuthElevesRouteWithChildren,
  AuthEtablissementsRoute: AuthEtablissementsRouteWithChildren,
  AuthExamensNationauxRoute: AuthExamensNationauxRoute,
  AuthFilieresRoute: AuthFilieresRoute,
  AuthGroupesEtablissementsRoute: AuthGroupesEtablissementsRoute,
  AuthMatieresRoute: AuthMatieresRouteWithChildren,
  AuthModulesReportingRoute: AuthModulesReportingRoute,
  AuthModulesRhRoute: AuthModulesRhRoute,
  AuthNiveauxRoute: AuthNiveauxRoute,
  AuthNotesRoute: AuthNotesRoute,
  AuthParametresRoute: AuthParametresRoute,
  AuthPeriodesRoute: AuthPeriodesRouteWithChildren,
  AuthPersonnelRoute: AuthPersonnelRouteWithChildren,
  AuthProgrammesRoute: AuthProgrammesRoute,
  AuthResponsablesElevesRoute: AuthResponsablesElevesRoute,
  AuthSallesRoute: AuthSallesRouteWithChildren,
  AuthSpecialitesRoute: AuthSpecialitesRoute,
  AuthUtilisateursRoute: AuthUtilisateursRouteWithChildren,
  AuthAdminPermissionsRoute: AuthAdminPermissionsRoute,
  AuthAdminRolesRoute: AuthAdminRolesRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface authenticatedParametresStructureAcademiqueRouteRouteChildren {
  authenticatedParametresStructureAcademiqueCyclesRoute: typeof authenticatedParametresStructureAcademiqueCyclesRoute
  authenticatedParametresStructureAcademiqueDiplomesElevesRoute: typeof authenticatedParametresStructureAcademiqueDiplomesElevesRoute
  authenticatedParametresStructureAcademiqueExamensNationauxRoute: typeof authenticatedParametresStructureAcademiqueExamensNationauxRoute
  authenticatedParametresStructureAcademiqueFilieresRoute: typeof authenticatedParametresStructureAcademiqueFilieresRoute
  authenticatedParametresStructureAcademiqueNiveauxRoute: typeof authenticatedParametresStructureAcademiqueNiveauxRoute
}

const authenticatedParametresStructureAcademiqueRouteRouteChildren: authenticatedParametresStructureAcademiqueRouteRouteChildren =
  {
    authenticatedParametresStructureAcademiqueCyclesRoute:
      authenticatedParametresStructureAcademiqueCyclesRoute,
    authenticatedParametresStructureAcademiqueDiplomesElevesRoute:
      authenticatedParametresStructureAcademiqueDiplomesElevesRoute,
    authenticatedParametresStructureAcademiqueExamensNationauxRoute:
      authenticatedParametresStructureAcademiqueExamensNationauxRoute,
    authenticatedParametresStructureAcademiqueFilieresRoute:
      authenticatedParametresStructureAcademiqueFilieresRoute,
    authenticatedParametresStructureAcademiqueNiveauxRoute:
      authenticatedParametresStructureAcademiqueNiveauxRoute,
  }

const authenticatedParametresStructureAcademiqueRouteRouteWithChildren =
  authenticatedParametresStructureAcademiqueRouteRoute._addFileChildren(
    authenticatedParametresStructureAcademiqueRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  authenticatedParametresStructureAcademiqueRouteRoute:
    authenticatedParametresStructureAcademiqueRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
