/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUtilisateursRouteImport } from './routes/_auth.utilisateurs'
import { Route as AuthSpecialitesRouteImport } from './routes/_auth.specialites'
import { Route as AuthSallesRouteImport } from './routes/_auth.salles'
import { Route as AuthResponsablesElevesRouteImport } from './routes/_auth.responsables-eleves'
import { Route as AuthProgrammesRouteImport } from './routes/_auth.programmes'
import { Route as AuthPersonnelRouteImport } from './routes/_auth.personnel'
import { Route as AuthPeriodesRouteImport } from './routes/_auth.periodes'
import { Route as AuthParametresRouteImport } from './routes/_auth.parametres'
import { Route as AuthNotesRouteImport } from './routes/_auth.notes'
import { Route as AuthNiveauxRouteImport } from './routes/_auth.niveaux'
import { Route as AuthModulesRhRouteImport } from './routes/_auth.modules-rh'
import { Route as AuthModulesReportingRouteImport } from './routes/_auth.modules-reporting'
import { Route as AuthMatieresRouteImport } from './routes/_auth.matieres'
import { Route as AuthGroupesEtablissementsRouteImport } from './routes/_auth.groupes-etablissements'
import { Route as AuthFilieresRouteImport } from './routes/_auth.filieres'
import { Route as AuthExamensNationauxRouteImport } from './routes/_auth.examens-nationaux'
import { Route as AuthEtablissementsRouteImport } from './routes/_auth.etablissements'
import { Route as AuthEnseignantsRouteImport } from './routes/_auth/enseignants'
import { Route as AuthElevesRouteImport } from './routes/_auth.eleves'
import { Route as AuthDiplomesElevesRouteImport } from './routes/_auth.diplomes-eleves'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCyclesRouteImport } from './routes/_auth.cycles'
import { Route as AuthConfigurationRouteImport } from './routes/_auth/configuration'
import { Route as AuthCompetencesRouteImport } from './routes/_auth.competences'
import { Route as AuthClassesRouteImport } from './routes/_auth.classes'
import { Route as AuthChangePasswordRouteImport } from './routes/_auth/change-password'
import { Route as AuthBulletinsRouteImport } from './routes/_auth.bulletins'
import { Route as AuthApparenceRouteImport } from './routes/_auth.apparence'
import { Route as AuthAnneesScolairesRouteImport } from './routes/_auth.annees-scolaires'
import { Route as AuthSpecialitesIndexRouteImport } from './routes/_auth.specialites.index'
import { Route as AuthSallesIndexRouteImport } from './routes/_auth.salles.index'
import { Route as AuthPeriodesIndexRouteImport } from './routes/_auth.periodes.index'
import { Route as AuthNiveauxIndexRouteImport } from './routes/_auth.niveaux.index'
import { Route as AuthMatieresIndexRouteImport } from './routes/_auth.matieres.index'
import { Route as AuthFilieresIndexRouteImport } from './routes/_auth.filieres.index'
import { Route as AuthExamensNationauxIndexRouteImport } from './routes/_auth.examens-nationaux.index'
import { Route as AuthEtablissementsIndexRouteImport } from './routes/_auth.etablissements.index'
import { Route as AuthEnseignantsIndexRouteImport } from './routes/_auth/enseignants.index'
import { Route as AuthElevesIndexRouteImport } from './routes/_auth.eleves.index'
import { Route as AuthDiplomesElevesIndexRouteImport } from './routes/_auth.diplomes-eleves.index'
import { Route as AuthCyclesIndexRouteImport } from './routes/_auth.cycles.index'
import { Route as AuthCompetencesIndexRouteImport } from './routes/_auth.competences.index'
import { Route as AuthClassesIndexRouteImport } from './routes/_auth.classes.index'
import { Route as AuthAnneesScolairesIndexRouteImport } from './routes/_auth.annees-scolaires.index'
import { Route as AuthUtilisateursIdRouteImport } from './routes/_auth.utilisateurs.$id'
import { Route as AuthSpecialitesIdRouteImport } from './routes/_auth.specialites.$id'
import { Route as AuthSallesStatistiquesRouteImport } from './routes/_auth.salles.statistiques'
import { Route as AuthSallesSalleIdRouteImport } from './routes/_auth.salles.$salleId'
import { Route as AuthProgrammesIdRouteImport } from './routes/_auth/programmes.$id'
import { Route as AuthPersonnelIdRouteImport } from './routes/_auth.personnel.$id'
import { Route as AuthPeriodesIdRouteImport } from './routes/_auth.periodes.$id'
import { Route as AuthNiveauxIdRouteImport } from './routes/_auth.niveaux.$id'
import { Route as AuthMatieresIdRouteImport } from './routes/_auth.matieres.$id'
import { Route as AuthFilieresIdRouteImport } from './routes/_auth.filieres.$id'
import { Route as AuthExamensNationauxIdRouteImport } from './routes/_auth.examens-nationaux.$id'
import { Route as AuthEtablissementsIdRouteImport } from './routes/_auth.etablissements.$id'
import { Route as AuthEnseignantsIdRouteImport } from './routes/_auth/enseignants.$id'
import { Route as AuthElevesIdRouteImport } from './routes/_auth.eleves.$id'
import { Route as AuthDiplomesElevesIdRouteImport } from './routes/_auth.diplomes-eleves.$id'
import { Route as AuthCyclesIdRouteImport } from './routes/_auth.cycles.$id'
import { Route as AuthCompetencesIdRouteImport } from './routes/_auth.competences.$id'
import { Route as AuthClassesIdRouteImport } from './routes/_auth.classes.$id'
import { Route as AuthAnneesScolairesIdRouteImport } from './routes/_auth.annees-scolaires.$id'
import { Route as AuthAdminRolesRouteImport } from './routes/_auth.admin.roles'
import { Route as AuthAdminPermissionsRouteImport } from './routes/_auth.admin.permissions'
import { Route as authenticatedParametresStructureAcademiqueRouteRouteImport } from './routes/(authenticated)/parametres/structure-academique/route'
import { Route as authenticatedParametresStructureAcademiqueNiveauxRouteImport } from './routes/(authenticated)/parametres/structure-academique/niveaux'
import { Route as authenticatedParametresStructureAcademiqueFilieresRouteImport } from './routes/(authenticated)/parametres/structure-academique/filieres'
import { Route as authenticatedParametresStructureAcademiqueExamensNationauxRouteImport } from './routes/(authenticated)/parametres/structure-academique/examens-nationaux'
import { Route as authenticatedParametresStructureAcademiqueDiplomesElevesRouteImport } from './routes/(authenticated)/parametres/structure-academique/diplomes-eleves'
import { Route as authenticatedParametresStructureAcademiqueCyclesRouteImport } from './routes/(authenticated)/parametres/structure-academique/cycles'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUtilisateursRoute = AuthUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSpecialitesRoute = AuthSpecialitesRouteImport.update({
  id: '/specialites',
  path: '/specialites',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSallesRoute = AuthSallesRouteImport.update({
  id: '/salles',
  path: '/salles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResponsablesElevesRoute = AuthResponsablesElevesRouteImport.update({
  id: '/responsables-eleves',
  path: '/responsables-eleves',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProgrammesRoute = AuthProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPersonnelRoute = AuthPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPeriodesRoute = AuthPeriodesRouteImport.update({
  id: '/periodes',
  path: '/periodes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthParametresRoute = AuthParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotesRoute = AuthNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNiveauxRoute = AuthNiveauxRouteImport.update({
  id: '/niveaux',
  path: '/niveaux',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModulesRhRoute = AuthModulesRhRouteImport.update({
  id: '/modules-rh',
  path: '/modules-rh',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModulesReportingRoute = AuthModulesReportingRouteImport.update({
  id: '/modules-reporting',
  path: '/modules-reporting',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMatieresRoute = AuthMatieresRouteImport.update({
  id: '/matieres',
  path: '/matieres',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGroupesEtablissementsRoute =
  AuthGroupesEtablissementsRouteImport.update({
    id: '/groupes-etablissements',
    path: '/groupes-etablissements',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthFilieresRoute = AuthFilieresRouteImport.update({
  id: '/filieres',
  path: '/filieres',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExamensNationauxRoute = AuthExamensNationauxRouteImport.update({
  id: '/examens-nationaux',
  path: '/examens-nationaux',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEtablissementsRoute = AuthEtablissementsRouteImport.update({
  id: '/etablissements',
  path: '/etablissements',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEnseignantsRoute = AuthEnseignantsRouteImport.update({
  id: '/enseignants',
  path: '/enseignants',
  getParentRoute: () => AuthRoute,
} as any)
const AuthElevesRoute = AuthElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDiplomesElevesRoute = AuthDiplomesElevesRouteImport.update({
  id: '/diplomes-eleves',
  path: '/diplomes-eleves',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCyclesRoute = AuthCyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfigurationRoute = AuthConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompetencesRoute = AuthCompetencesRouteImport.update({
  id: '/competences',
  path: '/competences',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClassesRoute = AuthClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBulletinsRoute = AuthBulletinsRouteImport.update({
  id: '/bulletins',
  path: '/bulletins',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApparenceRoute = AuthApparenceRouteImport.update({
  id: '/apparence',
  path: '/apparence',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnneesScolairesRoute = AuthAnneesScolairesRouteImport.update({
  id: '/annees-scolaires',
  path: '/annees-scolaires',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSpecialitesIndexRoute = AuthSpecialitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSpecialitesRoute,
} as any)
const AuthSallesIndexRoute = AuthSallesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSallesRoute,
} as any)
const AuthPeriodesIndexRoute = AuthPeriodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPeriodesRoute,
} as any)
const AuthNiveauxIndexRoute = AuthNiveauxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthNiveauxRoute,
} as any)
const AuthMatieresIndexRoute = AuthMatieresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMatieresRoute,
} as any)
const AuthFilieresIndexRoute = AuthFilieresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthFilieresRoute,
} as any)
const AuthExamensNationauxIndexRoute =
  AuthExamensNationauxIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthExamensNationauxRoute,
  } as any)
const AuthEtablissementsIndexRoute = AuthEtablissementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthEtablissementsRoute,
} as any)
const AuthEnseignantsIndexRoute = AuthEnseignantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthEnseignantsRoute,
} as any)
const AuthElevesIndexRoute = AuthElevesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthElevesRoute,
} as any)
const AuthDiplomesElevesIndexRoute = AuthDiplomesElevesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDiplomesElevesRoute,
} as any)
const AuthCyclesIndexRoute = AuthCyclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthCyclesRoute,
} as any)
const AuthCompetencesIndexRoute = AuthCompetencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthCompetencesRoute,
} as any)
const AuthClassesIndexRoute = AuthClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthClassesRoute,
} as any)
const AuthAnneesScolairesIndexRoute =
  AuthAnneesScolairesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAnneesScolairesRoute,
  } as any)
const AuthUtilisateursIdRoute = AuthUtilisateursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthUtilisateursRoute,
} as any)
const AuthSpecialitesIdRoute = AuthSpecialitesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthSpecialitesRoute,
} as any)
const AuthSallesStatistiquesRoute = AuthSallesStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => AuthSallesRoute,
} as any)
const AuthSallesSalleIdRoute = AuthSallesSalleIdRouteImport.update({
  id: '/$salleId',
  path: '/$salleId',
  getParentRoute: () => AuthSallesRoute,
} as any)
const AuthProgrammesIdRoute = AuthProgrammesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthProgrammesRoute,
} as any)
const AuthPersonnelIdRoute = AuthPersonnelIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthPersonnelRoute,
} as any)
const AuthPeriodesIdRoute = AuthPeriodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthPeriodesRoute,
} as any)
const AuthNiveauxIdRoute = AuthNiveauxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthNiveauxRoute,
} as any)
const AuthMatieresIdRoute = AuthMatieresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthMatieresRoute,
} as any)
const AuthFilieresIdRoute = AuthFilieresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthFilieresRoute,
} as any)
const AuthExamensNationauxIdRoute = AuthExamensNationauxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthExamensNationauxRoute,
} as any)
const AuthEtablissementsIdRoute = AuthEtablissementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthEtablissementsRoute,
} as any)
const AuthEnseignantsIdRoute = AuthEnseignantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthEnseignantsRoute,
} as any)
const AuthElevesIdRoute = AuthElevesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthElevesRoute,
} as any)
const AuthDiplomesElevesIdRoute = AuthDiplomesElevesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthDiplomesElevesRoute,
} as any)
const AuthCyclesIdRoute = AuthCyclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthCyclesRoute,
} as any)
const AuthCompetencesIdRoute = AuthCompetencesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthCompetencesRoute,
} as any)
const AuthClassesIdRoute = AuthClassesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthClassesRoute,
} as any)
const AuthAnneesScolairesIdRoute = AuthAnneesScolairesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthAnneesScolairesRoute,
} as any)
const AuthAdminRolesRoute = AuthAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminPermissionsRoute = AuthAdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => AuthRoute,
} as any)
const authenticatedParametresStructureAcademiqueRouteRoute =
  authenticatedParametresStructureAcademiqueRouteRouteImport.update({
    id: '/(authenticated)/parametres/structure-academique',
    path: '/parametres/structure-academique',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedParametresStructureAcademiqueNiveauxRoute =
  authenticatedParametresStructureAcademiqueNiveauxRouteImport.update({
    id: '/niveaux',
    path: '/niveaux',
    getParentRoute: () => authenticatedParametresStructureAcademiqueRouteRoute,
  } as any)
const authenticatedParametresStructureAcademiqueFilieresRoute =
  authenticatedParametresStructureAcademiqueFilieresRouteImport.update({
    id: '/filieres',
    path: '/filieres',
    getParentRoute: () => authenticatedParametresStructureAcademiqueRouteRoute,
  } as any)
const authenticatedParametresStructureAcademiqueExamensNationauxRoute =
  authenticatedParametresStructureAcademiqueExamensNationauxRouteImport.update({
    id: '/examens-nationaux',
    path: '/examens-nationaux',
    getParentRoute: () => authenticatedParametresStructureAcademiqueRouteRoute,
  } as any)
const authenticatedParametresStructureAcademiqueDiplomesElevesRoute =
  authenticatedParametresStructureAcademiqueDiplomesElevesRouteImport.update({
    id: '/diplomes-eleves',
    path: '/diplomes-eleves',
    getParentRoute: () => authenticatedParametresStructureAcademiqueRouteRoute,
  } as any)
const authenticatedParametresStructureAcademiqueCyclesRoute =
  authenticatedParametresStructureAcademiqueCyclesRouteImport.update({
    id: '/cycles',
    path: '/cycles',
    getParentRoute: () => authenticatedParametresStructureAcademiqueRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/annees-scolaires': typeof AuthAnneesScolairesRouteWithChildren
  '/apparence': typeof AuthApparenceRoute
  '/bulletins': typeof AuthBulletinsRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/classes': typeof AuthClassesRouteWithChildren
  '/competences': typeof AuthCompetencesRouteWithChildren
  '/configuration': typeof AuthConfigurationRoute
  '/cycles': typeof AuthCyclesRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/diplomes-eleves': typeof AuthDiplomesElevesRouteWithChildren
  '/eleves': typeof AuthElevesRouteWithChildren
  '/enseignants': typeof AuthEnseignantsRouteWithChildren
  '/etablissements': typeof AuthEtablissementsRouteWithChildren
  '/examens-nationaux': typeof AuthExamensNationauxRouteWithChildren
  '/filieres': typeof AuthFilieresRouteWithChildren
  '/groupes-etablissements': typeof AuthGroupesEtablissementsRoute
  '/matieres': typeof AuthMatieresRouteWithChildren
  '/modules-reporting': typeof AuthModulesReportingRoute
  '/modules-rh': typeof AuthModulesRhRoute
  '/niveaux': typeof AuthNiveauxRouteWithChildren
  '/notes': typeof AuthNotesRoute
  '/parametres': typeof AuthParametresRoute
  '/periodes': typeof AuthPeriodesRouteWithChildren
  '/personnel': typeof AuthPersonnelRouteWithChildren
  '/programmes': typeof AuthProgrammesRouteWithChildren
  '/responsables-eleves': typeof AuthResponsablesElevesRoute
  '/salles': typeof AuthSallesRouteWithChildren
  '/specialites': typeof AuthSpecialitesRouteWithChildren
  '/utilisateurs': typeof AuthUtilisateursRouteWithChildren
  '/parametres/structure-academique': typeof authenticatedParametresStructureAcademiqueRouteRouteWithChildren
  '/admin/permissions': typeof AuthAdminPermissionsRoute
  '/admin/roles': typeof AuthAdminRolesRoute
  '/annees-scolaires/$id': typeof AuthAnneesScolairesIdRoute
  '/classes/$id': typeof AuthClassesIdRoute
  '/competences/$id': typeof AuthCompetencesIdRoute
  '/cycles/$id': typeof AuthCyclesIdRoute
  '/diplomes-eleves/$id': typeof AuthDiplomesElevesIdRoute
  '/eleves/$id': typeof AuthElevesIdRoute
  '/enseignants/$id': typeof AuthEnseignantsIdRoute
  '/etablissements/$id': typeof AuthEtablissementsIdRoute
  '/examens-nationaux/$id': typeof AuthExamensNationauxIdRoute
  '/filieres/$id': typeof AuthFilieresIdRoute
  '/matieres/$id': typeof AuthMatieresIdRoute
  '/niveaux/$id': typeof AuthNiveauxIdRoute
  '/periodes/$id': typeof AuthPeriodesIdRoute
  '/personnel/$id': typeof AuthPersonnelIdRoute
  '/programmes/$id': typeof AuthProgrammesIdRoute
  '/salles/$salleId': typeof AuthSallesSalleIdRoute
  '/salles/statistiques': typeof AuthSallesStatistiquesRoute
  '/specialites/$id': typeof AuthSpecialitesIdRoute
  '/utilisateurs/$id': typeof AuthUtilisateursIdRoute
  '/annees-scolaires/': typeof AuthAnneesScolairesIndexRoute
  '/classes/': typeof AuthClassesIndexRoute
  '/competences/': typeof AuthCompetencesIndexRoute
  '/cycles/': typeof AuthCyclesIndexRoute
  '/diplomes-eleves/': typeof AuthDiplomesElevesIndexRoute
  '/eleves/': typeof AuthElevesIndexRoute
  '/enseignants/': typeof AuthEnseignantsIndexRoute
  '/etablissements/': typeof AuthEtablissementsIndexRoute
  '/examens-nationaux/': typeof AuthExamensNationauxIndexRoute
  '/filieres/': typeof AuthFilieresIndexRoute
  '/matieres/': typeof AuthMatieresIndexRoute
  '/niveaux/': typeof AuthNiveauxIndexRoute
  '/periodes/': typeof AuthPeriodesIndexRoute
  '/salles/': typeof AuthSallesIndexRoute
  '/specialites/': typeof AuthSpecialitesIndexRoute
  '/parametres/structure-academique/cycles': typeof authenticatedParametresStructureAcademiqueCyclesRoute
  '/parametres/structure-academique/diplomes-eleves': typeof authenticatedParametresStructureAcademiqueDiplomesElevesRoute
  '/parametres/structure-academique/examens-nationaux': typeof authenticatedParametresStructureAcademiqueExamensNationauxRoute
  '/parametres/structure-academique/filieres': typeof authenticatedParametresStructureAcademiqueFilieresRoute
  '/parametres/structure-academique/niveaux': typeof authenticatedParametresStructureAcademiqueNiveauxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/apparence': typeof AuthApparenceRoute
  '/bulletins': typeof AuthBulletinsRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/configuration': typeof AuthConfigurationRoute
  '/dashboard': typeof AuthDashboardRoute
  '/groupes-etablissements': typeof AuthGroupesEtablissementsRoute
  '/modules-reporting': typeof AuthModulesReportingRoute
  '/modules-rh': typeof AuthModulesRhRoute
  '/notes': typeof AuthNotesRoute
  '/parametres': typeof AuthParametresRoute
  '/personnel': typeof AuthPersonnelRouteWithChildren
  '/programmes': typeof AuthProgrammesRouteWithChildren
  '/responsables-eleves': typeof AuthResponsablesElevesRoute
  '/utilisateurs': typeof AuthUtilisateursRouteWithChildren
  '/parametres/structure-academique': typeof authenticatedParametresStructureAcademiqueRouteRouteWithChildren
  '/admin/permissions': typeof AuthAdminPermissionsRoute
  '/admin/roles': typeof AuthAdminRolesRoute
  '/annees-scolaires/$id': typeof AuthAnneesScolairesIdRoute
  '/classes/$id': typeof AuthClassesIdRoute
  '/competences/$id': typeof AuthCompetencesIdRoute
  '/cycles/$id': typeof AuthCyclesIdRoute
  '/diplomes-eleves/$id': typeof AuthDiplomesElevesIdRoute
  '/eleves/$id': typeof AuthElevesIdRoute
  '/enseignants/$id': typeof AuthEnseignantsIdRoute
  '/etablissements/$id': typeof AuthEtablissementsIdRoute
  '/examens-nationaux/$id': typeof AuthExamensNationauxIdRoute
  '/filieres/$id': typeof AuthFilieresIdRoute
  '/matieres/$id': typeof AuthMatieresIdRoute
  '/niveaux/$id': typeof AuthNiveauxIdRoute
  '/periodes/$id': typeof AuthPeriodesIdRoute
  '/personnel/$id': typeof AuthPersonnelIdRoute
  '/programmes/$id': typeof AuthProgrammesIdRoute
  '/salles/$salleId': typeof AuthSallesSalleIdRoute
  '/salles/statistiques': typeof AuthSallesStatistiquesRoute
  '/specialites/$id': typeof AuthSpecialitesIdRoute
  '/utilisateurs/$id': typeof AuthUtilisateursIdRoute
  '/annees-scolaires': typeof AuthAnneesScolairesIndexRoute
  '/classes': typeof AuthClassesIndexRoute
  '/competences': typeof AuthCompetencesIndexRoute
  '/cycles': typeof AuthCyclesIndexRoute
  '/diplomes-eleves': typeof AuthDiplomesElevesIndexRoute
  '/eleves': typeof AuthElevesIndexRoute
  '/enseignants': typeof AuthEnseignantsIndexRoute
  '/etablissements': typeof AuthEtablissementsIndexRoute
  '/examens-nationaux': typeof AuthExamensNationauxIndexRoute
  '/filieres': typeof AuthFilieresIndexRoute
  '/matieres': typeof AuthMatieresIndexRoute
  '/niveaux': typeof AuthNiveauxIndexRoute
  '/periodes': typeof AuthPeriodesIndexRoute
  '/salles': typeof AuthSallesIndexRoute
  '/specialites': typeof AuthSpecialitesIndexRoute
  '/parametres/structure-academique/cycles': typeof authenticatedParametresStructureAcademiqueCyclesRoute
  '/parametres/structure-academique/diplomes-eleves': typeof authenticatedParametresStructureAcademiqueDiplomesElevesRoute
  '/parametres/structure-academique/examens-nationaux': typeof authenticatedParametresStructureAcademiqueExamensNationauxRoute
  '/parametres/structure-academique/filieres': typeof authenticatedParametresStructureAcademiqueFilieresRoute
  '/parametres/structure-academique/niveaux': typeof authenticatedParametresStructureAcademiqueNiveauxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/annees-scolaires': typeof AuthAnneesScolairesRouteWithChildren
  '/_auth/apparence': typeof AuthApparenceRoute
  '/_auth/bulletins': typeof AuthBulletinsRoute
  '/_auth/change-password': typeof AuthChangePasswordRoute
  '/_auth/classes': typeof AuthClassesRouteWithChildren
  '/_auth/competences': typeof AuthCompetencesRouteWithChildren
  '/_auth/configuration': typeof AuthConfigurationRoute
  '/_auth/cycles': typeof AuthCyclesRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/diplomes-eleves': typeof AuthDiplomesElevesRouteWithChildren
  '/_auth/eleves': typeof AuthElevesRouteWithChildren
  '/_auth/enseignants': typeof AuthEnseignantsRouteWithChildren
  '/_auth/etablissements': typeof AuthEtablissementsRouteWithChildren
  '/_auth/examens-nationaux': typeof AuthExamensNationauxRouteWithChildren
  '/_auth/filieres': typeof AuthFilieresRouteWithChildren
  '/_auth/groupes-etablissements': typeof AuthGroupesEtablissementsRoute
  '/_auth/matieres': typeof AuthMatieresRouteWithChildren
  '/_auth/modules-reporting': typeof AuthModulesReportingRoute
  '/_auth/modules-rh': typeof AuthModulesRhRoute
  '/_auth/niveaux': typeof AuthNiveauxRouteWithChildren
  '/_auth/notes': typeof AuthNotesRoute
  '/_auth/parametres': typeof AuthParametresRoute
  '/_auth/periodes': typeof AuthPeriodesRouteWithChildren
  '/_auth/personnel': typeof AuthPersonnelRouteWithChildren
  '/_auth/programmes': typeof AuthProgrammesRouteWithChildren
  '/_auth/responsables-eleves': typeof AuthResponsablesElevesRoute
  '/_auth/salles': typeof AuthSallesRouteWithChildren
  '/_auth/specialites': typeof AuthSpecialitesRouteWithChildren
  '/_auth/utilisateurs': typeof AuthUtilisateursRouteWithChildren
  '/(authenticated)/parametres/structure-academique': typeof authenticatedParametresStructureAcademiqueRouteRouteWithChildren
  '/_auth/admin/permissions': typeof AuthAdminPermissionsRoute
  '/_auth/admin/roles': typeof AuthAdminRolesRoute
  '/_auth/annees-scolaires/$id': typeof AuthAnneesScolairesIdRoute
  '/_auth/classes/$id': typeof AuthClassesIdRoute
  '/_auth/competences/$id': typeof AuthCompetencesIdRoute
  '/_auth/cycles/$id': typeof AuthCyclesIdRoute
  '/_auth/diplomes-eleves/$id': typeof AuthDiplomesElevesIdRoute
  '/_auth/eleves/$id': typeof AuthElevesIdRoute
  '/_auth/enseignants/$id': typeof AuthEnseignantsIdRoute
  '/_auth/etablissements/$id': typeof AuthEtablissementsIdRoute
  '/_auth/examens-nationaux/$id': typeof AuthExamensNationauxIdRoute
  '/_auth/filieres/$id': typeof AuthFilieresIdRoute
  '/_auth/matieres/$id': typeof AuthMatieresIdRoute
  '/_auth/niveaux/$id': typeof AuthNiveauxIdRoute
  '/_auth/periodes/$id': typeof AuthPeriodesIdRoute
  '/_auth/personnel/$id': typeof AuthPersonnelIdRoute
  '/_auth/programmes/$id': typeof AuthProgrammesIdRoute
  '/_auth/salles/$salleId': typeof AuthSallesSalleIdRoute
  '/_auth/salles/statistiques': typeof AuthSallesStatistiquesRoute
  '/_auth/specialites/$id': typeof AuthSpecialitesIdRoute
  '/_auth/utilisateurs/$id': typeof AuthUtilisateursIdRoute
  '/_auth/annees-scolaires/': typeof AuthAnneesScolairesIndexRoute
  '/_auth/classes/': typeof AuthClassesIndexRoute
  '/_auth/competences/': typeof AuthCompetencesIndexRoute
  '/_auth/cycles/': typeof AuthCyclesIndexRoute
  '/_auth/diplomes-eleves/': typeof AuthDiplomesElevesIndexRoute
  '/_auth/eleves/': typeof AuthElevesIndexRoute
  '/_auth/enseignants/': typeof AuthEnseignantsIndexRoute
  '/_auth/etablissements/': typeof AuthEtablissementsIndexRoute
  '/_auth/examens-nationaux/': typeof AuthExamensNationauxIndexRoute
  '/_auth/filieres/': typeof AuthFilieresIndexRoute
  '/_auth/matieres/': typeof AuthMatieresIndexRoute
  '/_auth/niveaux/': typeof AuthNiveauxIndexRoute
  '/_auth/periodes/': typeof AuthPeriodesIndexRoute
  '/_auth/salles/': typeof AuthSallesIndexRoute
  '/_auth/specialites/': typeof AuthSpecialitesIndexRoute
  '/(authenticated)/parametres/structure-academique/cycles': typeof authenticatedParametresStructureAcademiqueCyclesRoute
  '/(authenticated)/parametres/structure-academique/diplomes-eleves': typeof authenticatedParametresStructureAcademiqueDiplomesElevesRoute
  '/(authenticated)/parametres/structure-academique/examens-nationaux': typeof authenticatedParametresStructureAcademiqueExamensNationauxRoute
  '/(authenticated)/parametres/structure-academique/filieres': typeof authenticatedParametresStructureAcademiqueFilieresRoute
  '/(authenticated)/parametres/structure-academique/niveaux': typeof authenticatedParametresStructureAcademiqueNiveauxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/annees-scolaires'
    | '/apparence'
    | '/bulletins'
    | '/change-password'
    | '/classes'
    | '/competences'
    | '/configuration'
    | '/cycles'
    | '/dashboard'
    | '/diplomes-eleves'
    | '/eleves'
    | '/enseignants'
    | '/etablissements'
    | '/examens-nationaux'
    | '/filieres'
    | '/groupes-etablissements'
    | '/matieres'
    | '/modules-reporting'
    | '/modules-rh'
    | '/niveaux'
    | '/notes'
    | '/parametres'
    | '/periodes'
    | '/personnel'
    | '/programmes'
    | '/responsables-eleves'
    | '/salles'
    | '/specialites'
    | '/utilisateurs'
    | '/parametres/structure-academique'
    | '/admin/permissions'
    | '/admin/roles'
    | '/annees-scolaires/$id'
    | '/classes/$id'
    | '/competences/$id'
    | '/cycles/$id'
    | '/diplomes-eleves/$id'
    | '/eleves/$id'
    | '/enseignants/$id'
    | '/etablissements/$id'
    | '/examens-nationaux/$id'
    | '/filieres/$id'
    | '/matieres/$id'
    | '/niveaux/$id'
    | '/periodes/$id'
    | '/personnel/$id'
    | '/programmes/$id'
    | '/salles/$salleId'
    | '/salles/statistiques'
    | '/specialites/$id'
    | '/utilisateurs/$id'
    | '/annees-scolaires/'
    | '/classes/'
    | '/competences/'
    | '/cycles/'
    | '/diplomes-eleves/'
    | '/eleves/'
    | '/enseignants/'
    | '/etablissements/'
    | '/examens-nationaux/'
    | '/filieres/'
    | '/matieres/'
    | '/niveaux/'
    | '/periodes/'
    | '/salles/'
    | '/specialites/'
    | '/parametres/structure-academique/cycles'
    | '/parametres/structure-academique/diplomes-eleves'
    | '/parametres/structure-academique/examens-nationaux'
    | '/parametres/structure-academique/filieres'
    | '/parametres/structure-academique/niveaux'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/apparence'
    | '/bulletins'
    | '/change-password'
    | '/configuration'
    | '/dashboard'
    | '/groupes-etablissements'
    | '/modules-reporting'
    | '/modules-rh'
    | '/notes'
    | '/parametres'
    | '/personnel'
    | '/programmes'
    | '/responsables-eleves'
    | '/utilisateurs'
    | '/parametres/structure-academique'
    | '/admin/permissions'
    | '/admin/roles'
    | '/annees-scolaires/$id'
    | '/classes/$id'
    | '/competences/$id'
    | '/cycles/$id'
    | '/diplomes-eleves/$id'
    | '/eleves/$id'
    | '/enseignants/$id'
    | '/etablissements/$id'
    | '/examens-nationaux/$id'
    | '/filieres/$id'
    | '/matieres/$id'
    | '/niveaux/$id'
    | '/periodes/$id'
    | '/personnel/$id'
    | '/programmes/$id'
    | '/salles/$salleId'
    | '/salles/statistiques'
    | '/specialites/$id'
    | '/utilisateurs/$id'
    | '/annees-scolaires'
    | '/classes'
    | '/competences'
    | '/cycles'
    | '/diplomes-eleves'
    | '/eleves'
    | '/enseignants'
    | '/etablissements'
    | '/examens-nationaux'
    | '/filieres'
    | '/matieres'
    | '/niveaux'
    | '/periodes'
    | '/salles'
    | '/specialites'
    | '/parametres/structure-academique/cycles'
    | '/parametres/structure-academique/diplomes-eleves'
    | '/parametres/structure-academique/examens-nationaux'
    | '/parametres/structure-academique/filieres'
    | '/parametres/structure-academique/niveaux'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/_auth/annees-scolaires'
    | '/_auth/apparence'
    | '/_auth/bulletins'
    | '/_auth/change-password'
    | '/_auth/classes'
    | '/_auth/competences'
    | '/_auth/configuration'
    | '/_auth/cycles'
    | '/_auth/dashboard'
    | '/_auth/diplomes-eleves'
    | '/_auth/eleves'
    | '/_auth/enseignants'
    | '/_auth/etablissements'
    | '/_auth/examens-nationaux'
    | '/_auth/filieres'
    | '/_auth/groupes-etablissements'
    | '/_auth/matieres'
    | '/_auth/modules-reporting'
    | '/_auth/modules-rh'
    | '/_auth/niveaux'
    | '/_auth/notes'
    | '/_auth/parametres'
    | '/_auth/periodes'
    | '/_auth/personnel'
    | '/_auth/programmes'
    | '/_auth/responsables-eleves'
    | '/_auth/salles'
    | '/_auth/specialites'
    | '/_auth/utilisateurs'
    | '/(authenticated)/parametres/structure-academique'
    | '/_auth/admin/permissions'
    | '/_auth/admin/roles'
    | '/_auth/annees-scolaires/$id'
    | '/_auth/classes/$id'
    | '/_auth/competences/$id'
    | '/_auth/cycles/$id'
    | '/_auth/diplomes-eleves/$id'
    | '/_auth/eleves/$id'
    | '/_auth/enseignants/$id'
    | '/_auth/etablissements/$id'
    | '/_auth/examens-nationaux/$id'
    | '/_auth/filieres/$id'
    | '/_auth/matieres/$id'
    | '/_auth/niveaux/$id'
    | '/_auth/periodes/$id'
    | '/_auth/personnel/$id'
    | '/_auth/programmes/$id'
    | '/_auth/salles/$salleId'
    | '/_auth/salles/statistiques'
    | '/_auth/specialites/$id'
    | '/_auth/utilisateurs/$id'
    | '/_auth/annees-scolaires/'
    | '/_auth/classes/'
    | '/_auth/competences/'
    | '/_auth/cycles/'
    | '/_auth/diplomes-eleves/'
    | '/_auth/eleves/'
    | '/_auth/enseignants/'
    | '/_auth/etablissements/'
    | '/_auth/examens-nationaux/'
    | '/_auth/filieres/'
    | '/_auth/matieres/'
    | '/_auth/niveaux/'
    | '/_auth/periodes/'
    | '/_auth/salles/'
    | '/_auth/specialites/'
    | '/(authenticated)/parametres/structure-academique/cycles'
    | '/(authenticated)/parametres/structure-academique/diplomes-eleves'
    | '/(authenticated)/parametres/structure-academique/examens-nationaux'
    | '/(authenticated)/parametres/structure-academique/filieres'
    | '/(authenticated)/parametres/structure-academique/niveaux'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  authenticatedParametresStructureAcademiqueRouteRoute: typeof authenticatedParametresStructureAcademiqueRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/utilisateurs': {
      id: '/_auth/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AuthUtilisateursRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/specialites': {
      id: '/_auth/specialites'
      path: '/specialites'
      fullPath: '/specialites'
      preLoaderRoute: typeof AuthSpecialitesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/salles': {
      id: '/_auth/salles'
      path: '/salles'
      fullPath: '/salles'
      preLoaderRoute: typeof AuthSallesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/responsables-eleves': {
      id: '/_auth/responsables-eleves'
      path: '/responsables-eleves'
      fullPath: '/responsables-eleves'
      preLoaderRoute: typeof AuthResponsablesElevesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/programmes': {
      id: '/_auth/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof AuthProgrammesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/personnel': {
      id: '/_auth/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof AuthPersonnelRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/periodes': {
      id: '/_auth/periodes'
      path: '/periodes'
      fullPath: '/periodes'
      preLoaderRoute: typeof AuthPeriodesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/parametres': {
      id: '/_auth/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthParametresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notes': {
      id: '/_auth/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthNotesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/niveaux': {
      id: '/_auth/niveaux'
      path: '/niveaux'
      fullPath: '/niveaux'
      preLoaderRoute: typeof AuthNiveauxRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modules-rh': {
      id: '/_auth/modules-rh'
      path: '/modules-rh'
      fullPath: '/modules-rh'
      preLoaderRoute: typeof AuthModulesRhRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modules-reporting': {
      id: '/_auth/modules-reporting'
      path: '/modules-reporting'
      fullPath: '/modules-reporting'
      preLoaderRoute: typeof AuthModulesReportingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/matieres': {
      id: '/_auth/matieres'
      path: '/matieres'
      fullPath: '/matieres'
      preLoaderRoute: typeof AuthMatieresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/groupes-etablissements': {
      id: '/_auth/groupes-etablissements'
      path: '/groupes-etablissements'
      fullPath: '/groupes-etablissements'
      preLoaderRoute: typeof AuthGroupesEtablissementsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/filieres': {
      id: '/_auth/filieres'
      path: '/filieres'
      fullPath: '/filieres'
      preLoaderRoute: typeof AuthFilieresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/examens-nationaux': {
      id: '/_auth/examens-nationaux'
      path: '/examens-nationaux'
      fullPath: '/examens-nationaux'
      preLoaderRoute: typeof AuthExamensNationauxRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/etablissements': {
      id: '/_auth/etablissements'
      path: '/etablissements'
      fullPath: '/etablissements'
      preLoaderRoute: typeof AuthEtablissementsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/enseignants': {
      id: '/_auth/enseignants'
      path: '/enseignants'
      fullPath: '/enseignants'
      preLoaderRoute: typeof AuthEnseignantsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/eleves': {
      id: '/_auth/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof AuthElevesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/diplomes-eleves': {
      id: '/_auth/diplomes-eleves'
      path: '/diplomes-eleves'
      fullPath: '/diplomes-eleves'
      preLoaderRoute: typeof AuthDiplomesElevesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cycles': {
      id: '/_auth/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof AuthCyclesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/configuration': {
      id: '/_auth/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof AuthConfigurationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/competences': {
      id: '/_auth/competences'
      path: '/competences'
      fullPath: '/competences'
      preLoaderRoute: typeof AuthCompetencesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classes': {
      id: '/_auth/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthClassesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/change-password': {
      id: '/_auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/bulletins': {
      id: '/_auth/bulletins'
      path: '/bulletins'
      fullPath: '/bulletins'
      preLoaderRoute: typeof AuthBulletinsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/apparence': {
      id: '/_auth/apparence'
      path: '/apparence'
      fullPath: '/apparence'
      preLoaderRoute: typeof AuthApparenceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/annees-scolaires': {
      id: '/_auth/annees-scolaires'
      path: '/annees-scolaires'
      fullPath: '/annees-scolaires'
      preLoaderRoute: typeof AuthAnneesScolairesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/specialites/': {
      id: '/_auth/specialites/'
      path: '/'
      fullPath: '/specialites/'
      preLoaderRoute: typeof AuthSpecialitesIndexRouteImport
      parentRoute: typeof AuthSpecialitesRoute
    }
    '/_auth/salles/': {
      id: '/_auth/salles/'
      path: '/'
      fullPath: '/salles/'
      preLoaderRoute: typeof AuthSallesIndexRouteImport
      parentRoute: typeof AuthSallesRoute
    }
    '/_auth/periodes/': {
      id: '/_auth/periodes/'
      path: '/'
      fullPath: '/periodes/'
      preLoaderRoute: typeof AuthPeriodesIndexRouteImport
      parentRoute: typeof AuthPeriodesRoute
    }
    '/_auth/niveaux/': {
      id: '/_auth/niveaux/'
      path: '/'
      fullPath: '/niveaux/'
      preLoaderRoute: typeof AuthNiveauxIndexRouteImport
      parentRoute: typeof AuthNiveauxRoute
    }
    '/_auth/matieres/': {
      id: '/_auth/matieres/'
      path: '/'
      fullPath: '/matieres/'
      preLoaderRoute: typeof AuthMatieresIndexRouteImport
      parentRoute: typeof AuthMatieresRoute
    }
    '/_auth/filieres/': {
      id: '/_auth/filieres/'
      path: '/'
      fullPath: '/filieres/'
      preLoaderRoute: typeof AuthFilieresIndexRouteImport
      parentRoute: typeof AuthFilieresRoute
    }
    '/_auth/examens-nationaux/': {
      id: '/_auth/examens-nationaux/'
      path: '/'
      fullPath: '/examens-nationaux/'
      preLoaderRoute: typeof AuthExamensNationauxIndexRouteImport
      parentRoute: typeof AuthExamensNationauxRoute
    }
    '/_auth/etablissements/': {
      id: '/_auth/etablissements/'
      path: '/'
      fullPath: '/etablissements/'
      preLoaderRoute: typeof AuthEtablissementsIndexRouteImport
      parentRoute: typeof AuthEtablissementsRoute
    }
    '/_auth/enseignants/': {
      id: '/_auth/enseignants/'
      path: '/'
      fullPath: '/enseignants/'
      preLoaderRoute: typeof AuthEnseignantsIndexRouteImport
      parentRoute: typeof AuthEnseignantsRoute
    }
    '/_auth/eleves/': {
      id: '/_auth/eleves/'
      path: '/'
      fullPath: '/eleves/'
      preLoaderRoute: typeof AuthElevesIndexRouteImport
      parentRoute: typeof AuthElevesRoute
    }
    '/_auth/diplomes-eleves/': {
      id: '/_auth/diplomes-eleves/'
      path: '/'
      fullPath: '/diplomes-eleves/'
      preLoaderRoute: typeof AuthDiplomesElevesIndexRouteImport
      parentRoute: typeof AuthDiplomesElevesRoute
    }
    '/_auth/cycles/': {
      id: '/_auth/cycles/'
      path: '/'
      fullPath: '/cycles/'
      preLoaderRoute: typeof AuthCyclesIndexRouteImport
      parentRoute: typeof AuthCyclesRoute
    }
    '/_auth/competences/': {
      id: '/_auth/competences/'
      path: '/'
      fullPath: '/competences/'
      preLoaderRoute: typeof AuthCompetencesIndexRouteImport
      parentRoute: typeof AuthCompetencesRoute
    }
    '/_auth/classes/': {
      id: '/_auth/classes/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthClassesIndexRouteImport
      parentRoute: typeof AuthClassesRoute
    }
    '/_auth/annees-scolaires/': {
      id: '/_auth/annees-scolaires/'
      path: '/'
      fullPath: '/annees-scolaires/'
      preLoaderRoute: typeof AuthAnneesScolairesIndexRouteImport
      parentRoute: typeof AuthAnneesScolairesRoute
    }
    '/_auth/utilisateurs/$id': {
      id: '/_auth/utilisateurs/$id'
      path: '/$id'
      fullPath: '/utilisateurs/$id'
      preLoaderRoute: typeof AuthUtilisateursIdRouteImport
      parentRoute: typeof AuthUtilisateursRoute
    }
    '/_auth/specialites/$id': {
      id: '/_auth/specialites/$id'
      path: '/$id'
      fullPath: '/specialites/$id'
      preLoaderRoute: typeof AuthSpecialitesIdRouteImport
      parentRoute: typeof AuthSpecialitesRoute
    }
    '/_auth/salles/statistiques': {
      id: '/_auth/salles/statistiques'
      path: '/statistiques'
      fullPath: '/salles/statistiques'
      preLoaderRoute: typeof AuthSallesStatistiquesRouteImport
      parentRoute: typeof AuthSallesRoute
    }
    '/_auth/salles/$salleId': {
      id: '/_auth/salles/$salleId'
      path: '/$salleId'
      fullPath: '/salles/$salleId'
      preLoaderRoute: typeof AuthSallesSalleIdRouteImport
      parentRoute: typeof AuthSallesRoute
    }
    '/_auth/programmes/$id': {
      id: '/_auth/programmes/$id'
      path: '/$id'
      fullPath: '/programmes/$id'
      preLoaderRoute: typeof AuthProgrammesIdRouteImport
      parentRoute: typeof AuthProgrammesRoute
    }
    '/_auth/personnel/$id': {
      id: '/_auth/personnel/$id'
      path: '/$id'
      fullPath: '/personnel/$id'
      preLoaderRoute: typeof AuthPersonnelIdRouteImport
      parentRoute: typeof AuthPersonnelRoute
    }
    '/_auth/periodes/$id': {
      id: '/_auth/periodes/$id'
      path: '/$id'
      fullPath: '/periodes/$id'
      preLoaderRoute: typeof AuthPeriodesIdRouteImport
      parentRoute: typeof AuthPeriodesRoute
    }
    '/_auth/niveaux/$id': {
      id: '/_auth/niveaux/$id'
      path: '/$id'
      fullPath: '/niveaux/$id'
      preLoaderRoute: typeof AuthNiveauxIdRouteImport
      parentRoute: typeof AuthNiveauxRoute
    }
    '/_auth/matieres/$id': {
      id: '/_auth/matieres/$id'
      path: '/$id'
      fullPath: '/matieres/$id'
      preLoaderRoute: typeof AuthMatieresIdRouteImport
      parentRoute: typeof AuthMatieresRoute
    }
    '/_auth/filieres/$id': {
      id: '/_auth/filieres/$id'
      path: '/$id'
      fullPath: '/filieres/$id'
      preLoaderRoute: typeof AuthFilieresIdRouteImport
      parentRoute: typeof AuthFilieresRoute
    }
    '/_auth/examens-nationaux/$id': {
      id: '/_auth/examens-nationaux/$id'
      path: '/$id'
      fullPath: '/examens-nationaux/$id'
      preLoaderRoute: typeof AuthExamensNationauxIdRouteImport
      parentRoute: typeof AuthExamensNationauxRoute
    }
    '/_auth/etablissements/$id': {
      id: '/_auth/etablissements/$id'
      path: '/$id'
      fullPath: '/etablissements/$id'
      preLoaderRoute: typeof AuthEtablissementsIdRouteImport
      parentRoute: typeof AuthEtablissementsRoute
    }
    '/_auth/enseignants/$id': {
      id: '/_auth/enseignants/$id'
      path: '/$id'
      fullPath: '/enseignants/$id'
      preLoaderRoute: typeof AuthEnseignantsIdRouteImport
      parentRoute: typeof AuthEnseignantsRoute
    }
    '/_auth/eleves/$id': {
      id: '/_auth/eleves/$id'
      path: '/$id'
      fullPath: '/eleves/$id'
      preLoaderRoute: typeof AuthElevesIdRouteImport
      parentRoute: typeof AuthElevesRoute
    }
    '/_auth/diplomes-eleves/$id': {
      id: '/_auth/diplomes-eleves/$id'
      path: '/$id'
      fullPath: '/diplomes-eleves/$id'
      preLoaderRoute: typeof AuthDiplomesElevesIdRouteImport
      parentRoute: typeof AuthDiplomesElevesRoute
    }
    '/_auth/cycles/$id': {
      id: '/_auth/cycles/$id'
      path: '/$id'
      fullPath: '/cycles/$id'
      preLoaderRoute: typeof AuthCyclesIdRouteImport
      parentRoute: typeof AuthCyclesRoute
    }
    '/_auth/competences/$id': {
      id: '/_auth/competences/$id'
      path: '/$id'
      fullPath: '/competences/$id'
      preLoaderRoute: typeof AuthCompetencesIdRouteImport
      parentRoute: typeof AuthCompetencesRoute
    }
    '/_auth/classes/$id': {
      id: '/_auth/classes/$id'
      path: '/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof AuthClassesIdRouteImport
      parentRoute: typeof AuthClassesRoute
    }
    '/_auth/annees-scolaires/$id': {
      id: '/_auth/annees-scolaires/$id'
      path: '/$id'
      fullPath: '/annees-scolaires/$id'
      preLoaderRoute: typeof AuthAnneesScolairesIdRouteImport
      parentRoute: typeof AuthAnneesScolairesRoute
    }
    '/_auth/admin/roles': {
      id: '/_auth/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthAdminRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/permissions': {
      id: '/_auth/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthAdminPermissionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(authenticated)/parametres/structure-academique': {
      id: '/(authenticated)/parametres/structure-academique'
      path: '/parametres/structure-academique'
      fullPath: '/parametres/structure-academique'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/parametres/structure-academique/niveaux': {
      id: '/(authenticated)/parametres/structure-academique/niveaux'
      path: '/niveaux'
      fullPath: '/parametres/structure-academique/niveaux'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueNiveauxRouteImport
      parentRoute: typeof authenticatedParametresStructureAcademiqueRouteRoute
    }
    '/(authenticated)/parametres/structure-academique/filieres': {
      id: '/(authenticated)/parametres/structure-academique/filieres'
      path: '/filieres'
      fullPath: '/parametres/structure-academique/filieres'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueFilieresRouteImport
      parentRoute: typeof authenticatedParametresStructureAcademiqueRouteRoute
    }
    '/(authenticated)/parametres/structure-academique/examens-nationaux': {
      id: '/(authenticated)/parametres/structure-academique/examens-nationaux'
      path: '/examens-nationaux'
      fullPath: '/parametres/structure-academique/examens-nationaux'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueExamensNationauxRouteImport
      parentRoute: typeof authenticatedParametresStructureAcademiqueRouteRoute
    }
    '/(authenticated)/parametres/structure-academique/diplomes-eleves': {
      id: '/(authenticated)/parametres/structure-academique/diplomes-eleves'
      path: '/diplomes-eleves'
      fullPath: '/parametres/structure-academique/diplomes-eleves'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueDiplomesElevesRouteImport
      parentRoute: typeof authenticatedParametresStructureAcademiqueRouteRoute
    }
    '/(authenticated)/parametres/structure-academique/cycles': {
      id: '/(authenticated)/parametres/structure-academique/cycles'
      path: '/cycles'
      fullPath: '/parametres/structure-academique/cycles'
      preLoaderRoute: typeof authenticatedParametresStructureAcademiqueCyclesRouteImport
      parentRoute: typeof authenticatedParametresStructureAcademiqueRouteRoute
    }
  }
}

interface AuthAnneesScolairesRouteChildren {
  AuthAnneesScolairesIdRoute: typeof AuthAnneesScolairesIdRoute
  AuthAnneesScolairesIndexRoute: typeof AuthAnneesScolairesIndexRoute
}

const AuthAnneesScolairesRouteChildren: AuthAnneesScolairesRouteChildren = {
  AuthAnneesScolairesIdRoute: AuthAnneesScolairesIdRoute,
  AuthAnneesScolairesIndexRoute: AuthAnneesScolairesIndexRoute,
}

const AuthAnneesScolairesRouteWithChildren =
  AuthAnneesScolairesRoute._addFileChildren(AuthAnneesScolairesRouteChildren)

interface AuthClassesRouteChildren {
  AuthClassesIdRoute: typeof AuthClassesIdRoute
  AuthClassesIndexRoute: typeof AuthClassesIndexRoute
}

const AuthClassesRouteChildren: AuthClassesRouteChildren = {
  AuthClassesIdRoute: AuthClassesIdRoute,
  AuthClassesIndexRoute: AuthClassesIndexRoute,
}

const AuthClassesRouteWithChildren = AuthClassesRoute._addFileChildren(
  AuthClassesRouteChildren,
)

interface AuthCompetencesRouteChildren {
  AuthCompetencesIdRoute: typeof AuthCompetencesIdRoute
  AuthCompetencesIndexRoute: typeof AuthCompetencesIndexRoute
}

const AuthCompetencesRouteChildren: AuthCompetencesRouteChildren = {
  AuthCompetencesIdRoute: AuthCompetencesIdRoute,
  AuthCompetencesIndexRoute: AuthCompetencesIndexRoute,
}

const AuthCompetencesRouteWithChildren = AuthCompetencesRoute._addFileChildren(
  AuthCompetencesRouteChildren,
)

interface AuthCyclesRouteChildren {
  AuthCyclesIdRoute: typeof AuthCyclesIdRoute
  AuthCyclesIndexRoute: typeof AuthCyclesIndexRoute
}

const AuthCyclesRouteChildren: AuthCyclesRouteChildren = {
  AuthCyclesIdRoute: AuthCyclesIdRoute,
  AuthCyclesIndexRoute: AuthCyclesIndexRoute,
}

const AuthCyclesRouteWithChildren = AuthCyclesRoute._addFileChildren(
  AuthCyclesRouteChildren,
)

interface AuthDiplomesElevesRouteChildren {
  AuthDiplomesElevesIdRoute: typeof AuthDiplomesElevesIdRoute
  AuthDiplomesElevesIndexRoute: typeof AuthDiplomesElevesIndexRoute
}

const AuthDiplomesElevesRouteChildren: AuthDiplomesElevesRouteChildren = {
  AuthDiplomesElevesIdRoute: AuthDiplomesElevesIdRoute,
  AuthDiplomesElevesIndexRoute: AuthDiplomesElevesIndexRoute,
}

const AuthDiplomesElevesRouteWithChildren =
  AuthDiplomesElevesRoute._addFileChildren(AuthDiplomesElevesRouteChildren)

interface AuthElevesRouteChildren {
  AuthElevesIdRoute: typeof AuthElevesIdRoute
  AuthElevesIndexRoute: typeof AuthElevesIndexRoute
}

const AuthElevesRouteChildren: AuthElevesRouteChildren = {
  AuthElevesIdRoute: AuthElevesIdRoute,
  AuthElevesIndexRoute: AuthElevesIndexRoute,
}

const AuthElevesRouteWithChildren = AuthElevesRoute._addFileChildren(
  AuthElevesRouteChildren,
)

interface AuthEnseignantsRouteChildren {
  AuthEnseignantsIdRoute: typeof AuthEnseignantsIdRoute
  AuthEnseignantsIndexRoute: typeof AuthEnseignantsIndexRoute
}

const AuthEnseignantsRouteChildren: AuthEnseignantsRouteChildren = {
  AuthEnseignantsIdRoute: AuthEnseignantsIdRoute,
  AuthEnseignantsIndexRoute: AuthEnseignantsIndexRoute,
}

const AuthEnseignantsRouteWithChildren = AuthEnseignantsRoute._addFileChildren(
  AuthEnseignantsRouteChildren,
)

interface AuthEtablissementsRouteChildren {
  AuthEtablissementsIdRoute: typeof AuthEtablissementsIdRoute
  AuthEtablissementsIndexRoute: typeof AuthEtablissementsIndexRoute
}

const AuthEtablissementsRouteChildren: AuthEtablissementsRouteChildren = {
  AuthEtablissementsIdRoute: AuthEtablissementsIdRoute,
  AuthEtablissementsIndexRoute: AuthEtablissementsIndexRoute,
}

const AuthEtablissementsRouteWithChildren =
  AuthEtablissementsRoute._addFileChildren(AuthEtablissementsRouteChildren)

interface AuthExamensNationauxRouteChildren {
  AuthExamensNationauxIdRoute: typeof AuthExamensNationauxIdRoute
  AuthExamensNationauxIndexRoute: typeof AuthExamensNationauxIndexRoute
}

const AuthExamensNationauxRouteChildren: AuthExamensNationauxRouteChildren = {
  AuthExamensNationauxIdRoute: AuthExamensNationauxIdRoute,
  AuthExamensNationauxIndexRoute: AuthExamensNationauxIndexRoute,
}

const AuthExamensNationauxRouteWithChildren =
  AuthExamensNationauxRoute._addFileChildren(AuthExamensNationauxRouteChildren)

interface AuthFilieresRouteChildren {
  AuthFilieresIdRoute: typeof AuthFilieresIdRoute
  AuthFilieresIndexRoute: typeof AuthFilieresIndexRoute
}

const AuthFilieresRouteChildren: AuthFilieresRouteChildren = {
  AuthFilieresIdRoute: AuthFilieresIdRoute,
  AuthFilieresIndexRoute: AuthFilieresIndexRoute,
}

const AuthFilieresRouteWithChildren = AuthFilieresRoute._addFileChildren(
  AuthFilieresRouteChildren,
)

interface AuthMatieresRouteChildren {
  AuthMatieresIdRoute: typeof AuthMatieresIdRoute
  AuthMatieresIndexRoute: typeof AuthMatieresIndexRoute
}

const AuthMatieresRouteChildren: AuthMatieresRouteChildren = {
  AuthMatieresIdRoute: AuthMatieresIdRoute,
  AuthMatieresIndexRoute: AuthMatieresIndexRoute,
}

const AuthMatieresRouteWithChildren = AuthMatieresRoute._addFileChildren(
  AuthMatieresRouteChildren,
)

interface AuthNiveauxRouteChildren {
  AuthNiveauxIdRoute: typeof AuthNiveauxIdRoute
  AuthNiveauxIndexRoute: typeof AuthNiveauxIndexRoute
}

const AuthNiveauxRouteChildren: AuthNiveauxRouteChildren = {
  AuthNiveauxIdRoute: AuthNiveauxIdRoute,
  AuthNiveauxIndexRoute: AuthNiveauxIndexRoute,
}

const AuthNiveauxRouteWithChildren = AuthNiveauxRoute._addFileChildren(
  AuthNiveauxRouteChildren,
)

interface AuthPeriodesRouteChildren {
  AuthPeriodesIdRoute: typeof AuthPeriodesIdRoute
  AuthPeriodesIndexRoute: typeof AuthPeriodesIndexRoute
}

const AuthPeriodesRouteChildren: AuthPeriodesRouteChildren = {
  AuthPeriodesIdRoute: AuthPeriodesIdRoute,
  AuthPeriodesIndexRoute: AuthPeriodesIndexRoute,
}

const AuthPeriodesRouteWithChildren = AuthPeriodesRoute._addFileChildren(
  AuthPeriodesRouteChildren,
)

interface AuthPersonnelRouteChildren {
  AuthPersonnelIdRoute: typeof AuthPersonnelIdRoute
}

const AuthPersonnelRouteChildren: AuthPersonnelRouteChildren = {
  AuthPersonnelIdRoute: AuthPersonnelIdRoute,
}

const AuthPersonnelRouteWithChildren = AuthPersonnelRoute._addFileChildren(
  AuthPersonnelRouteChildren,
)

interface AuthProgrammesRouteChildren {
  AuthProgrammesIdRoute: typeof AuthProgrammesIdRoute
}

const AuthProgrammesRouteChildren: AuthProgrammesRouteChildren = {
  AuthProgrammesIdRoute: AuthProgrammesIdRoute,
}

const AuthProgrammesRouteWithChildren = AuthProgrammesRoute._addFileChildren(
  AuthProgrammesRouteChildren,
)

interface AuthSallesRouteChildren {
  AuthSallesSalleIdRoute: typeof AuthSallesSalleIdRoute
  AuthSallesStatistiquesRoute: typeof AuthSallesStatistiquesRoute
  AuthSallesIndexRoute: typeof AuthSallesIndexRoute
}

const AuthSallesRouteChildren: AuthSallesRouteChildren = {
  AuthSallesSalleIdRoute: AuthSallesSalleIdRoute,
  AuthSallesStatistiquesRoute: AuthSallesStatistiquesRoute,
  AuthSallesIndexRoute: AuthSallesIndexRoute,
}

const AuthSallesRouteWithChildren = AuthSallesRoute._addFileChildren(
  AuthSallesRouteChildren,
)

interface AuthSpecialitesRouteChildren {
  AuthSpecialitesIdRoute: typeof AuthSpecialitesIdRoute
  AuthSpecialitesIndexRoute: typeof AuthSpecialitesIndexRoute
}

const AuthSpecialitesRouteChildren: AuthSpecialitesRouteChildren = {
  AuthSpecialitesIdRoute: AuthSpecialitesIdRoute,
  AuthSpecialitesIndexRoute: AuthSpecialitesIndexRoute,
}

const AuthSpecialitesRouteWithChildren = AuthSpecialitesRoute._addFileChildren(
  AuthSpecialitesRouteChildren,
)

interface AuthUtilisateursRouteChildren {
  AuthUtilisateursIdRoute: typeof AuthUtilisateursIdRoute
}

const AuthUtilisateursRouteChildren: AuthUtilisateursRouteChildren = {
  AuthUtilisateursIdRoute: AuthUtilisateursIdRoute,
}

const AuthUtilisateursRouteWithChildren =
  AuthUtilisateursRoute._addFileChildren(AuthUtilisateursRouteChildren)

interface AuthRouteChildren {
  AuthAnneesScolairesRoute: typeof AuthAnneesScolairesRouteWithChildren
  AuthApparenceRoute: typeof AuthApparenceRoute
  AuthBulletinsRoute: typeof AuthBulletinsRoute
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthClassesRoute: typeof AuthClassesRouteWithChildren
  AuthCompetencesRoute: typeof AuthCompetencesRouteWithChildren
  AuthConfigurationRoute: typeof AuthConfigurationRoute
  AuthCyclesRoute: typeof AuthCyclesRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDiplomesElevesRoute: typeof AuthDiplomesElevesRouteWithChildren
  AuthElevesRoute: typeof AuthElevesRouteWithChildren
  AuthEnseignantsRoute: typeof AuthEnseignantsRouteWithChildren
  AuthEtablissementsRoute: typeof AuthEtablissementsRouteWithChildren
  AuthExamensNationauxRoute: typeof AuthExamensNationauxRouteWithChildren
  AuthFilieresRoute: typeof AuthFilieresRouteWithChildren
  AuthGroupesEtablissementsRoute: typeof AuthGroupesEtablissementsRoute
  AuthMatieresRoute: typeof AuthMatieresRouteWithChildren
  AuthModulesReportingRoute: typeof AuthModulesReportingRoute
  AuthModulesRhRoute: typeof AuthModulesRhRoute
  AuthNiveauxRoute: typeof AuthNiveauxRouteWithChildren
  AuthNotesRoute: typeof AuthNotesRoute
  AuthParametresRoute: typeof AuthParametresRoute
  AuthPeriodesRoute: typeof AuthPeriodesRouteWithChildren
  AuthPersonnelRoute: typeof AuthPersonnelRouteWithChildren
  AuthProgrammesRoute: typeof AuthProgrammesRouteWithChildren
  AuthResponsablesElevesRoute: typeof AuthResponsablesElevesRoute
  AuthSallesRoute: typeof AuthSallesRouteWithChildren
  AuthSpecialitesRoute: typeof AuthSpecialitesRouteWithChildren
  AuthUtilisateursRoute: typeof AuthUtilisateursRouteWithChildren
  AuthAdminPermissionsRoute: typeof AuthAdminPermissionsRoute
  AuthAdminRolesRoute: typeof AuthAdminRolesRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnneesScolairesRoute: AuthAnneesScolairesRouteWithChildren,
  AuthApparenceRoute: AuthApparenceRoute,
  AuthBulletinsRoute: AuthBulletinsRoute,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthClassesRoute: AuthClassesRouteWithChildren,
  AuthCompetencesRoute: AuthCompetencesRouteWithChildren,
  AuthConfigurationRoute: AuthConfigurationRoute,
  AuthCyclesRoute: AuthCyclesRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDiplomesElevesRoute: AuthDiplomesElevesRouteWithChildren,
  AuthElevesRoute: AuthElevesRouteWithChildren,
  AuthEnseignantsRoute: AuthEnseignantsRouteWithChildren,
  AuthEtablissementsRoute: AuthEtablissementsRouteWithChildren,
  AuthExamensNationauxRoute: AuthExamensNationauxRouteWithChildren,
  AuthFilieresRoute: AuthFilieresRouteWithChildren,
  AuthGroupesEtablissementsRoute: AuthGroupesEtablissementsRoute,
  AuthMatieresRoute: AuthMatieresRouteWithChildren,
  AuthModulesReportingRoute: AuthModulesReportingRoute,
  AuthModulesRhRoute: AuthModulesRhRoute,
  AuthNiveauxRoute: AuthNiveauxRouteWithChildren,
  AuthNotesRoute: AuthNotesRoute,
  AuthParametresRoute: AuthParametresRoute,
  AuthPeriodesRoute: AuthPeriodesRouteWithChildren,
  AuthPersonnelRoute: AuthPersonnelRouteWithChildren,
  AuthProgrammesRoute: AuthProgrammesRouteWithChildren,
  AuthResponsablesElevesRoute: AuthResponsablesElevesRoute,
  AuthSallesRoute: AuthSallesRouteWithChildren,
  AuthSpecialitesRoute: AuthSpecialitesRouteWithChildren,
  AuthUtilisateursRoute: AuthUtilisateursRouteWithChildren,
  AuthAdminPermissionsRoute: AuthAdminPermissionsRoute,
  AuthAdminRolesRoute: AuthAdminRolesRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface authenticatedParametresStructureAcademiqueRouteRouteChildren {
  authenticatedParametresStructureAcademiqueCyclesRoute: typeof authenticatedParametresStructureAcademiqueCyclesRoute
  authenticatedParametresStructureAcademiqueDiplomesElevesRoute: typeof authenticatedParametresStructureAcademiqueDiplomesElevesRoute
  authenticatedParametresStructureAcademiqueExamensNationauxRoute: typeof authenticatedParametresStructureAcademiqueExamensNationauxRoute
  authenticatedParametresStructureAcademiqueFilieresRoute: typeof authenticatedParametresStructureAcademiqueFilieresRoute
  authenticatedParametresStructureAcademiqueNiveauxRoute: typeof authenticatedParametresStructureAcademiqueNiveauxRoute
}

const authenticatedParametresStructureAcademiqueRouteRouteChildren: authenticatedParametresStructureAcademiqueRouteRouteChildren =
  {
    authenticatedParametresStructureAcademiqueCyclesRoute:
      authenticatedParametresStructureAcademiqueCyclesRoute,
    authenticatedParametresStructureAcademiqueDiplomesElevesRoute:
      authenticatedParametresStructureAcademiqueDiplomesElevesRoute,
    authenticatedParametresStructureAcademiqueExamensNationauxRoute:
      authenticatedParametresStructureAcademiqueExamensNationauxRoute,
    authenticatedParametresStructureAcademiqueFilieresRoute:
      authenticatedParametresStructureAcademiqueFilieresRoute,
    authenticatedParametresStructureAcademiqueNiveauxRoute:
      authenticatedParametresStructureAcademiqueNiveauxRoute,
  }

const authenticatedParametresStructureAcademiqueRouteRouteWithChildren =
  authenticatedParametresStructureAcademiqueRouteRoute._addFileChildren(
    authenticatedParametresStructureAcademiqueRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  authenticatedParametresStructureAcademiqueRouteRoute:
    authenticatedParametresStructureAcademiqueRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
