#!/bin/bash

# =====================================================
# eLISAschool - Guide de Test Rapide des Modules
# =====================================================
# Ce script affiche les commandes pour tester chaque module
# =====================================================

echo "=========================================="
echo "  eLISAschool - Test Rapide des Modules"
echo "=========================================="
echo ""

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}📋 ÉTAPE 1 : Lancer les services${NC}"
echo ""
echo "  # Terminal 1 - Backend"
echo "  cd backend"
echo "  npm run dev"
echo ""
echo "  # Terminal 2 - Frontend"
echo "  cd frontend"
echo "  npm run dev"
echo ""

echo -e "${BLUE}📋 ÉTAPE 2 : Accéder aux modules${NC}"
echo ""
echo -e "${GREEN}✅ Modules Structurels:${NC}"
echo "  1. http://localhost:7000/etablissements"
echo "     → Créer, modifier, supprimer des établissements"
echo ""
echo "  2. http://localhost:7000/cycles"
echo "     → Gérer les cycles éducatifs (Primaire, Collège, Lycée)"
echo ""
echo "  3. http://localhost:7000/niveaux"
echo "     → Créer des niveaux avec sélection de cycle"
echo ""
echo "  4. http://localhost:7000/classes"
echo "     → Gérer les classes avec effectifs"
echo ""
echo "  5. http://localhost:7000/annees-scolaires"
echo "     → Créer et activer les années scolaires"
echo ""
echo "  6. http://localhost:7000/matieres"
echo "     → Gérer les matières avec coefficients"
echo ""
echo "  7. http://localhost:7000/personnel"
echo "     → Gérer les membres du personnel"
echo ""
echo "  8. http://localhost:7000/admin/roles"
echo "     → Administrer les rôles et permissions"
echo ""

echo -e "${BLUE}📋 ÉTAPE 3 : Tester les fonctionnalités${NC}"
echo ""
echo -e "${YELLOW}Pour chaque module, tester :${NC}"
echo ""
echo "  ✅ Création"
echo "     - Cliquer sur 'Nouveau/Nouvelle'"
echo "     - Remplir le formulaire (champs * requis)"
echo "     - Vérifier la validation (messages d'erreur)"
echo "     - Cliquer 'Créer' et vérifier le tableau"
echo ""
echo "  ✅ Lecture"
echo "     - Vérifier l'affichage dans le tableau"
echo "     - Tester la recherche"
echo "     - Tester la pagination"
echo "     - Cliquer 'Voir' pour les détails"
echo ""
echo "  ✅ Modification"
echo "     - Cliquer sur l'icône ✏️ (Modifier)"
echo "     - Modifier les champs"
echo "     - Cliquer 'Enregistrer'"
echo "     - Vérifier les changements"
echo ""
echo "  ✅ Suppression"
echo "     - Cliquer sur l'icône 🗑️ (Supprimer)"
echo "     - Confirmer dans le dialog"
echo "     - Vérifier la disparition du tableau"
echo ""

echo -e "${BLUE}📋 ÉTAPE 4 : Vérifier la sécurité RBAC${NC}"
echo ""
echo "  1. Se connecter comme ADMIN"
echo "     → Tous les boutons doivent être visibles"
echo ""
echo "  2. Se connecter comme ENSEIGNANT"
echo "     → Boutons créer/modifier/supprimer masqués"
echo "     → Seul 'Voir' devrait être disponible"
echo ""
echo "  3. Tester l'accès direct aux routes"
echo "     → Sans permission = redirection"
echo ""

echo -e "${BLUE}📋 ÉTAPE 5 : Tester l'UX${NC}"
echo ""
echo "  ✅ Responsive"
echo "     - Redimensionner la fenêtre"
echo "     - Tester sur mobile (F12 → Device Toolbar)"
echo ""
echo "  ✅ Animations"
echo "     - Observer les transitions Framer Motion"
echo "     - Vérifier les hover effects sur boutons"
echo ""
echo "  ✅ Tooltips"
echo "     - Survoler les boutons d'actions"
echo "     - Vérifier les infobulles"
echo ""
echo "  ✅ États de chargement"
echo "     - Recharger la page (Ctrl+R)"
echo "     - Observer les skeletons/loading"
echo ""

echo -e "${BLUE}📋 ÉTAPE 6 : Tests avancés${NC}"
echo ""
echo "  ✅ Établissements"
echo "     - Créer avec tous les types (Laïc, Catholique, etc.)"
echo "     - Tester les sous-systèmes (Francophone, Anglophone, Biculturel)"
echo "     - Vérifier validation email"
echo ""
echo "  ✅ Cycles"
echo "     - Créer cycle avec ordre"
echo "     - Vérifier auto-génération code"
echo ""
echo "  ✅ Niveaux"
echo "     - Sélectionner cycle dans dropdown"
echo "     - Vérifier auto-génération code UTF-8"
echo ""
echo "  ✅ Années Scolaires"
echo "     - Créer année avec dates"
echo "     - Tester bouton Power (activer)"
echo "     - Vérifier calcul durée automatique"
echo ""
echo "  ✅ Rôles"
echo "     - Créer rôle avec permissions"
echo "     - Voir onglet Utilisateurs"
echo "     - Tester filtres (Système/Personnalisés)"
echo ""

echo "=========================================="
echo "  Checklist de Validation"
echo "=========================================="
echo ""
echo "  Module         | CRUD | Modal | RBAC | UX  | Notes"
echo "  ---------------|------|-------|------|-----|------"
echo "  Établissements |  ⬜  |  ⬜   |  ⬜  |  ⬜  | Nouveau"
echo "  Cycles         |  ⬜  |  ⬜   |  ⬜  |  ⬜  | Amélioré"
echo "  Niveaux        |  ⬜  |  ⬜   |  ⬜  |  ⬜  | Amélioré"
echo "  Classes        |  ⬜  |  ⬜   |  ⬜  |  ⬜  | Amélioré"
echo "  Années Scol.   |  ⬜  |  ⬜   |  ⬜  |  ⬜  | Amélioré"
echo "  Matières       |  ⬜  |  ⬜   |  ⬜  |  ⬜  | Amélioré"
echo "  Personnel      |  ⬜  |  ⬜   |  ⬜  |  ⬜  | Vérifié"
echo "  Rôles          |  ⬜  |  ⬜   |  ⬜  |  ⬜  | Complet"
echo ""
echo -e "${GREEN}✅ Cocher chaque case après test réussi${NC}"
echo ""
echo "=========================================="
echo "  Ressources Utiles"
echo "=========================================="
echo ""
echo "  📚 Guide de développement : frontend/GUIDE-DEVELOPPEMENT.md"
echo "  📊 Rapport final        : RAPPORT-FINAL-MODULES-FRONTEND.md"
echo "  🔍 Script vérification  : scripts/verify-modules.sh"
echo ""
echo "=========================================="
